### ISSUE TITLE
Crafting tab. Incorrect journals amount

### ISSUE THREAD

**Issue by BloodySupport** [Triky313/AlbionOnline-StatisticsAnalysis#106]
All items has incorrect required journal amount.
In example:
Master's Avalonian Fishing Rod T6.0 give only 2160 crafting fame and journal need 14400 crafting fame but StatisticsAnalysis show what required journal amount is 9.45

**Comment by BloodySupport** [comment]
I used 4.6.0 and 4.6.4

**Comment by Triky313** [comment]
Thanks for the report.
