### ISSUE TITLE
Hi Dev/Mod:

### ISSUE THREAD

**Issue by dpsmeter** [Triky313/AlbionOnline-StatisticsAnalysis#107]
**Describe the bug**

-------The party doesn't seem to refresh the players and it only shows me. It does not show my party member nor their damage meter. Not sure if I did the settings right. May I get some help ?

**Comment by Triky313** [comment]
Which version of the program are you using?
Which Windows are you using?
Do you have npcap installed?

**Comment by dpsmeter** [comment]
Hi :

Currently using the latest version *StatisticsAnalysis-AlbionOnline-v4.0.1-x64.zip*

Yes I have npcap installed, as well as .NET

**Comment by Triky313** [comment]
This is the latest version https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/releases/download/4.6.4/StatisticsAnalysis-AlbionOnline-v4.6.4-x64.zip
Please try this version!

**Comment by dpsmeter** [comment]
Hi :

This version works, the damage meter shows a bit too many names. It has 5x my name and other players name as well. How would I fix this ?

**Comment by dpsmeter** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/95012291/144290662-8293408f-c1e9-4227-9f79-c960ef511971.png)

**Comment by Triky313** [comment]
Damage Meter fixed!
https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/releases/tag/4.6.5
