### ISSUE TITLE
DPS Meter is Not Working While Using Geforce Now

### ISSUE THREAD

**Issue by trandnt42** [Triky313/AlbionOnline-StatisticsAnalysis#109]
I know that DPS meter can only pull data locally from the PC. For Geforce Now, I am aware that I'm playing Albion on another computer and it streams to my PC, so DPS Meter cannot pull data locally. Is there a way to fix or work around this issue?

**Comment by Triky313** [comment]
No. Technically, you have to have access to the Nvidia server and read out the data there. That is strictly not possible for us.
