### ISSUE TITLE
Improvement about Loot Log

### ISSUE THREAD

**Issue by Vanezkun** [Triky313/AlbionOnline-StatisticsAnalysis#110]
**Is your feature request related to a problem? Please describe.**

- About loot log, i don't really like it because i can't see who is the real rat (in zvz).
- Also i don't really like if using item ID, example "T4_CAPEITEM_FW_FORTSTERLING@3" instead of "T4.3 Fort Sterling Cape"

**Describe the solution you'd like**

- For the first one, make like "top looter" with name and amount of items that they takes.
- The second one maybe like replace word or something like that

**Describe alternatives you've considered**
I don't understand coding, so sorry.

**Comment by Triky313** [comment]
The CSV file that can be exported is intended for this page: https://matheus.sampaio.us/ao-loot-logger-viewer/

The names are the real item names, but I can add an option where the correct InGame Item Name is displayed, depending on the language.

Top Looter sounds interesting. I'm thinking of something.
