### ISSUE TITLE
Load full item info crawls, hangs or aborts

### ISSUE THREAD

**Issue by biship** [Triky313/AlbionOnline-StatisticsAnalysis#111]
Running ver 4.6.7.26845.
It progresses a few hundred, slows down and then either stops, craws or eventually just stops.
I have to restart the app to resume, thankfully it picks up from where it left off.
I've restarted the client 4-5 times and over the last few hours I am up to 4435/7969.
Where is this data coming from? Can I use another source?

**Comment by Triky313** [comment]
This data comes directly from Albion Online servers. Unfortunately there is a timeout at some point after loading. I will think of a better solution to get the data and without interruptions.

**Comment by biship** [comment]
What's the endpoint?
And actually, what is the data??

**Comment by Triky313** [comment]
You can find all possible endpoints here: https://www.tools4albion.com/api_info.php
For example, the data looks like this: https://gameinfo.albiononline.com/api/gameinfo/items/T8_MEAL_STEW/data

But as soon as you load more than 80-100 data in quick succession, the API temporarily blocks access so that the Albion servers do not become DDoS.

**Comment by biship** [comment]
What is your client just used the dumps?
https://github.com/broderickhyman/ao-bin-dumps
Looks like you need at items.json & localization.json.
Have the client check if the change date of those files has changed and just download and parse the entire file(s).
The client would have the entire file in seconds instead of hours trying to pull items one-by-one.

**Comment by Triky313** [comment]
That's where most of the information is, that's right. But currently I haven't found a good solution to have the items structured in a list. 

There are a lot of sub-categories and different items. I'll have to put in a lot of work to get what I need.

But yes, you are right, that will probably be the best solution.
