### ISSUE TITLE
Tracking Mailbox

### ISSUE THREAD

**Issue by Dibort** [Triky313/AlbionOnline-StatisticsAnalysis#112]
I saw some mailbox references such as GetMailInfos in the enum OperationCodes and NewUnreadMails in EventCodes enum.
I think it could be usefull to track mail data for traders/crafters. I write one by one all mail trade info in a spreadsheet for example.

If it's out of the scope of the project or too much effort...I'll try to fork it and implement it myself but I'm not very confident with my C# right now.

**Comment by Triky313** [comment]
I already have an eye on the market mails. At the moment there are a lot of other things to do. But it would help if I could get the exact event and operation code.

In addition, I have to think about what exactly should be done with it. Show total profit from sales or something?

**Comment by Dibort** [comment]
I've been doing that for [albiondata-client](https://github.com/broderickhyman/albiondata-client) and I've seen that there's no specific event as it's a manual action (is it like that?), the photon msg type is 2 so it's an OperationRequest followed by its [OperationResponse](https://github.com/broderickhyman/photon_spectator/blob/713aea094aa8d113e3a5189c30a85ab37cccdb34/photon_command.go#L23).
The exact operation is 171 (ReadMail). That's for when you directly open the mail, the other event/operations don't have the inside mail info, so the info can't be tracked the exact same way as fame etc as you need to manually open that mail...

Total profit from sales would be nice, but the **mail id** should be checked in case you open the same mail multiple times.
Besides the total profit it'll be nice to display row per row info as some kind of trade history, something like:
Buy/Sell, Item, Price, Units, Total, Total + Tax...

Currently in my spreadsheet I'm displaying:
City | Buy/Sell | Date | Item | Price | Units | Total | Tax | Total + Tax | Real price/unit
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

But in the event/operation info I don't see the city nor the date of the mail and that's irritating me, operation 169 has mail info but only ids, sender, read or not, mail type...

Can't check it now, tomorrow I'll dig more into it.

**Comment by Triky313** [comment]
So, I've already made some preparations.

Currently I can assign the mails based on the entire list.
Unfortunately I couldn't find the time. The only thing that comes close is this from [168]getMailInfos :
11:[637852747555964630 637852641241345990 637852580102847960 637852420676002090 637852343125116360 637852323860168170]

The first 5-6 numbers are the same and it keeps increasing, but I haven't been able to time it yet.

**GetMailInfosResponse**:
```
public class MailInfoObject
{
    public MailInfoObject(Guid? guid, long mailId, string clusterIndex, MailType mailType)
    {
        Guid = guid;
        MailId = mailId;
        ClusterIndex = clusterIndex;
        MailType = mailType;
    }

    public Guid? Guid { get; set; }
    public long MailId { get; set; }
    public string ClusterIndex { get; set; }
    public MailType MailType { get; set; }
}
```

**ReadMailResponse**:
```
public long MailId;
public string Content;
```

**string Content becomes Content**:
```
public class MailContent
{
    public int Quantity { get; set; }
    public string UniqueItemName { get; set; }
    public long InternalTotalPrice { get; set; }
    public long InternalUnitPrice { get; set; }
    [JsonIgnore]
    public FixPoint TotalPrice => FixPoint.FromInternalValue(InternalTotalPrice);
    [JsonIgnore]
    public FixPoint UnitPrice => FixPoint.FromInternalValue(InternalUnitPrice);
}
```
