### ISSUE TITLE
hide crack between dungeon tab in Dungeons

### ISSUE THREAD

**Issue by PurpleGale** [Triky313/AlbionOnline-StatisticsAnalysis#114]
**Is your feature request related to a problem? Please describe.**
Dungeon stat window has a little crack between two windows. I use 5.0.1

**Describe the solution you'd like**
Increase height and hide this crack

**Describe alternatives you've considered**
decrease distance between dungeon stats

**Additional context**
split between dungeons
![изображение](https://user-images.githubusercontent.com/90148755/147369069-f52beada-027d-4d7c-a1f9-460f6328bfc4.png)
![изображение](https://user-images.githubusercontent.com/90148755/147369119-3060d716-a929-4433-bd06-9487b91340c7.png)

**Comment by Triky313** [comment]
Instead of the empty space in between, I have now added a border with a subtle color.
Removing it completely does not look good, so you would no longer recognize the delimitation of the respective dungeon correctly.
