### ISSUE TITLE
Too many requests, close a few windows or wait a few minutes.

### ISSUE THREAD

**Issue by ManalpX** [Triky313/AlbionOnline-StatisticsAnalysis#119]
![image](https://user-images.githubusercontent.com/93259559/148398602-e59572a2-f79e-47c0-8044-378313450785.png)
What does it mean? This error keeps popping up when looking at items.

**Comment by Triky313** [comment]
This means that you have sent too many item requests to the API server in a short time.
The Albion Online Data Project server allows 100-200 requests per minute, I believe.

Each window makes a query, depending on how the refresh rate is set, this can happen every 5 seconds. If you look at a lot of items very quickly or have many item windows open at the same time, a blocker can briefly appear.

**Comment by ManalpX** [comment]
Actually, I don't look at many items, max 3 items once every 5 minutes.

Is there any way to prevent this?

**Comment by ManalpX** [comment]
I forgot to ask. How many operations does each item I look at correspond to on the API server?

**Comment by Triky313** [comment]
When the window opens, there is a request.
If you change the quality of the item in the window, there is a new request so that new data can be loaded for the diagram.

Normally that shouldn't be a problem, maybe you are connecting to the API from somewhere else?

**Comment by ManalpX** [comment]
![image](https://user-images.githubusercontent.com/93259559/148408670-60770daf-675e-446f-80da-9e9fb8024ad2.png)

Is there any problem in this part?

**Comment by Triky313** [comment]
Unfortunately I cannot understand your language. You'd have to show me that in English.

**Comment by ManalpX** [comment]
![image](https://user-images.githubusercontent.com/93259559/148416139-b69ed3bd-0a1a-48cb-8128-c15c0d9880df.png)

**Comment by ManalpX** [comment]
Are u there?

**Comment by Triky313** [comment]
Looks okay so far.
It would be best to test it for a few more days. That shouldn't happen that often.

**Comment by ManalpX** [comment]
This problem continues when I transfer my items to the bank quickly in the game.

While checking the items, I started to think if it would be helpful to close the Albion Data Client. I do not know

**Comment by Triky313** [comment]
Do you have an error log for me?

**Comment by Triky313** [comment]
Closed due to inactivity
