### ISSUE TITLE
Respec per hr not calculated correctly

### ISSUE THREAD

**Issue by biship** [Triky313/AlbionOnline-StatisticsAnalysis#120]
5.2.0
Start SA
Kill mobs
Totals and per hr for fame, silver and faction show correctly
Respec has a value, but shows 0/h.
Sometime later the per hour value starts for respec appears and seems to be calculating from *then*, and not from the start of the app like the other per hr calculations.
Screen shot is after about 17 mins.
![image](https://user-images.githubusercontent.com/1854029/149367623-7622874b-8d15-47fd-8182-c7c805aee749.png)

**Comment by biship** [comment]
The amount of respec also isn't calculated correctly. It's about 1/4 of what it really is.

**Comment by Triky313** [comment]
Bug has been fixed in and will come in the next update. https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/commit/14c28831977a29e37a80a15c43dbad9136ec2b58
