### ISSUE TITLE
Crafting changes

### ISSUE THREAD

**Issue by biship** [Triky313/AlbionOnline-StatisticsAnalysis#122]
Can you consider these?

1. Adding crafting screen to mounts & processed raw materials (such as planks)
2. On the crafting tab, add a "Get prices" button, and an ability to select from which Market Place
3. On the crafting tab, changing the quality does not change the resources required.
4. On the crafting tab, add the ability to pick the other resources that could be used to craft the item.

**Comment by Triky313** [comment]
1. Is done and comes with the next update after v5.2.0 
2. I made a new issue #123 
3. The quality of the item does not change either
4. You certainly mean like with Albion2d, I won't be able to install that for time and priority reasons.

**Comment by biship** [comment]
5.3.2
1. Not fixed. Check Cedar Planks (T5). No crafting tab.
2. Works, nice! However if the value is still zero after selecting the location dropdown I don't know if it's still trying to get the data, or if there isn't any data available. It would be great if we could select a default location that was used every time we open the crafting tab for each item so that we don't have to select a loc every time, for every component.
3. Oh yeah, this is broken.
4. Yeah, some items have multiple recipes. You seem to only show one.

**Comment by Triky313** [comment]
1. Resource Crafting (Refinement) will come later
2. The tool takes values that are available. If there are none, a 0 comes, this is normal
3. Nothing is broken, the quality of an item has nothing to do with the resources
4. Oh the recipes, all items should now be visible there. Also the new artifacts from the challenge chests
