### ISSUE TITLE
Improvements to Dungeons Tab

### ISSUE THREAD

**Issue by biship** [Triky313/AlbionOnline-StatisticsAnalysis#124]
5.30
1. Allow us to edit (overwrite) the tier. I just did a T8 map in a V BZ and SAT marks it as V.
2. In addition to the above, allow us to set the quality & tier. eg 7.0, 7.1, 7.2, 7.3.
3. Add a notes/comment text field so we can make notes per dungeon
4. Add a "Loot Worth" INT field to each Dungeon where we can enter the silver value of loot obtained. (as this isn't tracked)
5. Include the above 4 items in you JSON (for us EXCEL nerds)
6. Icon is missing for Might
7. Mouse over tool tip for all icons do not work (except fame)

Thanks for the great program BTW :)

**Comment by Triky313** [comment]
1. I'll try to find a better solution in the future. It would be best for something like this to happen automatically
2. The same as the first
3. What is this needed for? what do you want to note down?
4. There will also be a feature that automatically adds up all the values
5. Theoretically, an Excel export for dungeons would be possible. The only question is how many would actually use it. I should start a poll here
6. https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/issues/125
7. Where exactly, in which area?

**Comment by biship** [comment]
> 1. I'll try to find a better solution in the future. It would be best for something like this to happen automatically. Thanks!
> 2. The same as the first. Thanks!
> 3. What is this needed for? what do you want to note down? "Took a bathroom break". Just notes. If you dont see value, I dont have a compelling reason other then something that may have impacted the speed/efficiency would be good to note.
> 4. There will also be a feature that automatically adds up all the values. SAT doesnt log loot for me, so I import your dungeonruns.json into excel and manually add loot worth to each run. It would be good if I could just enter this on each run in SAT.
> 5. Theoretically, an Excel export for dungeons would be possible. The only question is how many would actually use it. I should start a poll here. The dungeonruns.json already does this for me. I just import that into Excel. It would be great when/if you add #1 to #4 it's also in the json.
> 6. [Icon is missing for Might in dungeon tracker #125](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/issues/125)
> 7. Where exactly, in which area? Each dungeon run on the dungeons tab.

**Comment by Triky313** [comment]
7. Fixed here: https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/commit/60891c31373d363bce4cb2880c0359e57b1b48f9

**Comment by biship** [comment]
5.3.2
7. Faction points and standing are missing tool tips
Also the tool tip delay is so long!

**Comment by Triky313** [comment]
I'll take another look, thanks.

**Comment by Triky313** [comment]
Added missing tooltips. I cannot influence the opening of a tooltip.
For further suggestions please open a new issue.
