### ISSUE TITLE
Crafting tab bugs & feature requests

### ISSUE THREAD

**Issue by biship** [Triky313/AlbionOnline-StatisticsAnalysis#129]
5.4.0
Crafting tab for Giant Stag T4.0
1. Usage fee does not change the Grand Total. The Crafting tax always stays at -0
2. Can you add a check box to toggle "other costs" to be per item (and when not toggled, it defaults to how it is now).
3. Journal costs is always -0 and I don't even see a way to change/influence.
4. I assume crafting bonus is resource return rate? It doesn't allow decimals. eg. Crafting this item in Lymhurst has a RRR of 15.2%
5. Able to show Amount of Focus used in the calculation?
6. Rename "Setup fee" to "Auction House Setup Fee:"
7. Rename "Crafting tax" to "Usage fee"

**Comment by Triky313** [comment]
1. It works for me, can you take a screenshot or something and tell me which item this happens with?
2. For your own productions or possible productions?
3. It works for me, what exactly do you see? Please more information!
4. No, that's the number that can be found on the minimap at the top right when you hover over the fields with the mouse.
![image](https://user-images.githubusercontent.com/14247773/152576881-224e30c8-cdc0-4b83-8b68-9bed68f17a11.png)
5. This is a new feature, please open a separate issue for it!
6. and 7. This probably applies to the English language en-US correct?

**Comment by biship** [comment]
I did list the item - Giant Stag T4.0
![image](https://user-images.githubusercontent.com/1854029/152583814-db064927-a741-4af6-99d7-50ca4a14d5ca.png)

1. I've entered 5400 Usage fee. It's stays as 0 "Crafting Tax" on the right. Changing the 5400 to 0 or 9999 does nothing to the right side (for any value).
2. I don't know what you are asking. If I set 100 in "Other costs" and change the item quantity, it's always 100 on the right. Sometimes that's fine. Other times that is a per item cost. So, I'd like to be able to enable/disable it to be per item.
3. See above screen shot. Journal costs is -0. There is no way to change it. 
4. Ok. I understand, thanks.
5. Will do.
6. Yes
7. Yes

**Comment by Triky313** [comment]
Okay, it's basically about crafting mounts. In fact, there still seems to be a problem with the calculation of the costs. I'll take a look
Other costs simply stands for buff food or teleport costs, e.g. something like that. Qol features will follow once bugs are fixed
