### ISSUE TITLE
cannot be displayed  .Mainland Chinese players  

### ISSUE THREAD

**Issue by Flexj001** [Triky313/AlbionOnline-StatisticsAnalysis#131]
error  
TOOLTASKS
GET_ITEMS_JSON
GET_ITEM_LIST_JSON

**Comment by Flexj001** [comment]
Dear, can you help players in mainland China use this software

**Comment by Flexj001** [comment]
please

**Comment by Flexj001** [comment]
cannot be displayed   DPS  data

**Comment by Flexj001** [comment]
Mainland Chinese players must use accelerators to play

**Comment by Triky313** [comment]
I'm sorry but the tool doesn't work with VPN or ExitLag.

**Comment by Flexj001** [comment]
OK  think u
