### ISSUE TITLE
Search across items in banks / tabs (via storage history window)

### ISSUE THREAD

**Issue by nazymko** [Triky313/AlbionOnline-StatisticsAnalysis#137]
**Is your feature request related to a problem? Please describe.**
It would be good to have the ability to find where specific items are (in what bank, in what tab) 

**Describe the solution you'd like**
Storage History window could have a search bar and show all tabs where specific items are (one mamonth in Thetford, another in personal island ex. )

**Comment by EuAmoCafeh** [comment]
Good idea ! i like it !
