### ISSUE TITLE
Chat friendly dps meter copy button(s)

### ISSUE THREAD

**Issue by Triky313** [Triky313/AlbionOnline-StatisticsAnalysis#139]
Chat friendly dps meter copy button(s). One message can have 160 characters. At the moment only the top 3 and half of the 4th dps can be copied most of the time.

Possible ways:

1) 1.Name - XX.YY% 2.Name - XX.YY% 3.Name - XX.YY% 4.Name - XX.YY% 5.Name - XX.YY% 6.Name - XX.YY% 7.Name - XX.YY% 8.Name - XX.YY% 9.Name - XX.YY% 10.Name - XX.YY%  <-- something similar, also could have extra 1-2 buttons. First would copy top 1-6 players, 2nd button top 7-12 or something. If we calculate with an average 8 characters long name, we could copy to the chat the top 8 dps. (1.NameName - XX.YY% 2.NameName - XX.YY% 3.NameName - XX.YY% 4.NameName - XX.YY% 5.NameName - XX.YY% 6.NameName - XX.YY% 7.NameName - XX.YY% 8.NameName - XX.YY%  <--- 159 characters).

Maybe could just use a "CharacterName".substring(0,8). 8 characters should be enough to not mix up 2 players.

2) Keep the format but much more buttons.

**Comment by EuAmoCafeh** [comment]
I think measuring the top 8 is more than enough. If you had the option to show them all and quickly copy the ones at the top, or to select which ones you want to copy.

**Comment by Triky313** [comment]
This is an idea from a user on Discord. I'll take another look at what works and what doesn't.
But yes, you're right, 8 players should definitely be enough.

**Comment by EuAmoCafeh** [comment]
> This is an idea from a user on Discord. I'll take another look at what works and what doesn't. But yes, you're right, 8 players should definitely be enough.

Could you post the discord link, the last time I tried, the link was down.

**Comment by Triky313** [comment]
https://discord.com/channels/772406813438115891/772408333280739348/967812286569938954

**Comment by EuAmoCafeh** [comment]
> https://discord.com/channels/772406813438115891/772408333280739348/967812286569938954
This syain i dont have acess to this channel 
![image](https://user-images.githubusercontent.com/103466580/165838150-bb911d71-b8f6-4644-b2fe-239a58268593.png)

**Comment by Triky313** [comment]
Please PN me on Discord. Triky313#1831

**Comment by EuAmoCafeh** [comment]
I can't send a message, it says there may be an error.

    Em quinta-feira, 28 de abril de 2022 19:04:19 AMT, Aaron Schultz ***@***.***> escreveu:  
 
 


Please PN me on Discord. Triky313#1831

**Comment by EuAmoCafeh** [comment]
In the error description it says '' Unsuccessful friend request. Hmm, it didn't work. Check the capitalization, spelling, spaces and numbers to make sure everything is correct. ''It's not a problem on my discord because I've added people recently.Anything this is my discord: Azzann#5317


    Em sexta-feira, 29 de abril de 2022 05:47:02 AMT, Aaron Schultz ***@***.***> escreveu:  
 
 


You can't message me to people in Discord? In which country are you?
I really can't help you there, I don't know why you can't write, write to Discord support!

**Comment by Triky313** [comment]
I send you a friend request.

**Comment by Triky313** [comment]
We currently have the following situation:

Depending on which filter was selected, different values can be present in the clipboard. I've tried enabling more reduced text with Short Value Choice in the settings, but I've come to the conclusion that this isn't a good solution.

I don't want to add any more buttons at the moment. The copy button was not added for displaying the text ingame, but for the Ava community who want to post their damage numbers without a screenshot.

If there are any further ideas or suggestions, the issue can be opened again.
