### ISSUE TITLE
Auto Update problem

### ISSUE THREAD

**Issue by EuAmoCafeh** [Triky313/AlbionOnline-StatisticsAnalysis#140]
I'm having this problem when I try to update by automatic update, I think I didn't change anything inside the application to cause this problem, in the last update I had the same problem and I downloaded it manually, so I didn't report it the other time I believe that maybe it was some silly problem.
<img width="844" alt="Screenshot_1" src="https://user-images.githubusercontent.com/103466580/165792857-9a7003e0-d64b-40b3-ba48-e8d60400c726.png">

**Comment by Triky313** [comment]
You seem to have such problems more often, is it possible that your internet is partially blocked? If you are from Russia, some things might not work correctly at the moment.

**Comment by Triky313** [comment]
You seem to have such problems more often, is it possible that your internet is partially blocked?

**Comment by Triky313** [comment]
If you have further problems, please open the issue here again.
