### ISSUE TITLE
StatisticsAnalysis-AlbionOnline-v5.8.1-x64

### ISSUE THREAD

**Issue by dpsmeter** [Triky313/AlbionOnline-StatisticsAnalysis#142]
**Describe the bug**

After update of this program. The program won't open.

**Comment by Triky313** [comment]
Many players are currently having a problem with the tool starting after the last update **v5.8.1**.

There are currently two possible solutions.
1. Install .NET Desktop Runtime 6.0.4 or higher **https://dotnet.microsoft.com/en-us/download/dotnet/6.0**
2. If point 1 didn't help, you can copy a **global.json** into the tool folder, so it should work first. 
Create a file named: **global.json**
Put this content in it:
```
{
"sdk": {
"version": "6.0.100",
"rollForward": "disable"
}
}
```

Sorry for the inconvenience, unfortunately there are currently some problems with Microsoft's .net libraries.

**Comment by Triky313** [comment]
Please download the current update manually and copy and replace all files into your broken tool folder.
https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/releases/tag/5.8.2
