### ISSUE TITLE
Write a more precise and up to date install procedure

### ISSUE THREAD

**Issue by Tyrben** [Triky313/AlbionOnline-StatisticsAnalysis#143]
**Is your feature request related to a problem? Please describe.**
The install instructions are unclear.

**Describe the solution you'd like**
Detail the precise version of .Net 6.X needed. (SDK, runtime...)
Tell if an higher version is compatible or not.
Give a way to test in the requisits are satisfied.
Put a screen shot of the microsoft page (could be in another page.md).

**Describe alternatives you've considered**
Automatize the installation of this pre requisits.
Put AlbionOnline-StatisticsAnalysis in an installer.

**Additional context**

**Comment by Triky313** [comment]
An installer is currently out of the question. The effort is too great and the benefits too small.
I implemented a **Getting Started** in the README.md. Added more specific information, hopefully easier to understand.
