### ISSUE TITLE
Dungeon sorting and Dungeon identification

### ISSUE THREAD

**Issue by GildedS** [Triky313/AlbionOnline-StatisticsAnalysis#149]
It would be pretty handy to be able to sort  the dungeons listed in the dungeons tab by:
Fame per hour
Fame earned
Silver by hour
Silver earned
Might per hour
Might earned
Favour per hour
Favour earned

It'd also be really cool if the dungeons listed could be tagged with the actual tier (and the multiplier for upgraded dungeons) of the  mobs in them, seeing that I do T7 dungeon maps but the listed tiers are of the zones they spawn in (usually 6 or 5)

**Comment by Triky313** [comment]
Sorting shouldn't be a problem.
However, I've been looking for a solution for a long time to find the correct level for the dungeon. I will keep working on it.

**Comment by Triky313** [comment]
Sorting is initially not implemented. Tier and level can now be recognized.
With 834f09b720c3fdb81cbdd062e87df7a1a6643166 tier and level filtering was added
