### ISSUE TITLE
language file not found

### ISSUE THREAD

**Issue by angelika-draczynska** [Triky313/AlbionOnline-StatisticsAnalysis#152]
Hi, Im getting those errors when trying to open the statistic tool. 
I installed everything what was mentioned.
![unknown3](https://user-images.githubusercontent.com/52296399/179327199-9a6e1cff-04fa-4585-93ea-51ba7685c71f.png)
![unknown2](https://user-images.githubusercontent.com/52296399/179327202-b45f5833-7767-45e4-b65a-3dab173ea6e8.png)

**Comment by Triky313** [comment]
Is in your tool main folder the folder Languages with this files on the screenshot?
![image](https://user-images.githubusercontent.com/14247773/179328651-a34e9b7a-adf1-4e20-85dc-c5b143e2a2ac.png)

If not, please download the newest version here again and start the tool.
https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/releases/download/5.9.4/StatisticsAnalysis-AlbionOnline-v5.9.4-x64.zip

If you continue to have problems, please let me know again.

**Comment by angelika-draczynska** [comment]
Yes, my tool main folder have this files like on ur screenshot.

also I downloaded the newest version and still the same problem.

**Comment by Triky313** [comment]
Did you extract the folder before running the .exe?

**Comment by angelika-draczynska** [comment]
Yes.

**Comment by Triky313** [comment]
Please download the latest version here again https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/releases/download/5.10.2/StatisticsAnalysis-AlbionOnline-v5.10.2-x64.zip and extract all files to a folder.

Then try again to start the tool!
