### ISSUE TITLE
Misunderstanding on the new pre release feature

### ISSUE THREAD

**Issue by GildedS** [Triky313/AlbionOnline-StatisticsAnalysis#153]
Hi, i think there was a misunderstanding on the new looted chest feature (Resolved issue  #148). What i meant by dungeon chests was solo chests, and not static dungeon chests. Also i suggested a chest logger to log the contents of said chest, not to keep track of what kind of chests was opened. If that's not possible as of this moment, then perhaps adding solo dungeon chests into the looted chest logger would be nice. Thank you for your time

**Comment by Triky313** [comment]
I was well aware that you would like to have the loot tracked in the chests. At the present time, this cannot be implemented without big effort. That's why I implemented the current solution.

A lot has changed in the game around chests lately, so I'll put more energy into that later.

**Comment by GildedS** [comment]
> I was well aware that you would like to have the loot tracked in the chests. At the present time, this cannot be implemented without big effort. That's why I implemented the current solution.
> 
> A lot has changed in the game around chests lately, so I'll put more energy into that later.

That's fair, you're doing wonderfully rn so don't push yourself. But to the other point, would it be possible to add solo dungeon chests to the Looted chests part of the dashboard?

**Comment by Triky313** [comment]
Technically it should be possible to see loot from chests. Regardless of solo dungeons, this feature will be useful and I'm trying to implement it.

**Comment by GildedS** [comment]
> Technically it should be possible to see loot from chests. Regardless of solo dungeons, this feature will be useful and I'm trying to implement it.

That's great to hear, I'm hella sure that you of all people can figure it out. But just to be clear, will you be adding a tally for solo dungeon chests to the dashboard, like what you did for these four 
![2022-07-19 02_58_12-AlbionOnline - StatisticsAnalysisTool](https://user-images.githubusercontent.com/75071007/179583734-558ead0a-3b47-4616-aaf8-ec5d29f78bf5.png)

**Comment by Triky313** [comment]
I can add that for solo and group dungeon yes. I'm currently testing whether the static dungeons are being tracked correctly, but random dungeons can definitely be added.

**Comment by Triky313** [comment]
Further discussions about chest loot logs can be found here #69 

With the 5.11.0 update, solo and group dungeons have been included in the dashboard
