### ISSUE TITLE
reset the parsing on different encounters

### ISSUE THREAD

**Issue by lucasbnucci** [Triky313/AlbionOnline-StatisticsAnalysis#156]
Right now, we have to manually reset the DPS meter every time we enter in a new dungeon/pack of mobs too see the damage in that specific pull.

It would be nice if there was a possibility for the parsing reset after the pack is killed or when a boss fight start

**Comment by Triky313** [comment]
Added in commit 81782f050f0cb5d6afb95543bda8d946eedb31bf
