### ISSUE TITLE
Error with npcap

### ISSUE THREAD

**Issue by portoreal** [Triky313/AlbionOnline-StatisticsAnalysis#157]
**Describe the bug**
npcap 1.7.0 installed but is not recognized.
![image](https://user-images.githubusercontent.com/30160625/182638438-d7ae0ff9-97d4-48ef-9873-96900332e953.png)

**Comment by Triky313** [comment]
What version is the tool?
Which Windows are you using?

Please check whether WinPcap is installed, if so, uninstall it!
Otherwise reinstall NPcap again!
