### ISSUE TITLE
Tracking is partially active 

### ISSUE THREAD

**Issue by jupik87** [Triky313/AlbionOnline-StatisticsAnalysis#159]
hi when I turn on the program it pops up at the top tracking is partially active please change the zone does anyone know how to fix it? Thank you in advance

**Comment by Triky313** [comment]
It's written there, change the zone!

**Comment by jupik87** [comment]
I know that it says that I should change, but I don't know myself too much and I don't know how to change it

**Comment by Triky313** [comment]
You just have to start the tool and then change a map in the game. For example, going from Fort Sterling to Fort Sterling Bank.
