### ISSUE TITLE
App don't work

### ISSUE THREAD

**Issue by Valkalas** [Triky313/AlbionOnline-StatisticsAnalysis#16]
Hi,

18 Jan - app working
22 Jan - app start and crash, don't work

In windows journal for app have 2 errors:

1)

Имя сбойного приложения: StatisticsAnalysisTool.exe, версия: 2.4.0.0, метка времени: 0x5fefaa4b
Имя сбойного модуля: KERNELBASE.dll, версия: 10.0.19041.662, метка времени: 0xec58f015
Код исключения: 0xe0434352
Смещение ошибки: 0x000000000002d759
Идентификатор сбойного процесса: 0x12e4
Время запуска сбойного приложения: 0x01d6f0dfae04e0d7
Путь сбойного приложения: F:\SAAO\StatisticsAnalysisTool.exe
Путь сбойного модуля: C:\Windows\System32\KERNELBASE.dll
Идентификатор отчета: c8d14dc5-ff1c-47c4-bfa8-fda2d1f7c461
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом: 

2)

Приложение: StatisticsAnalysisTool.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за необработанного исключения.
Сведения об исключении: System.ArgumentOutOfRangeException
   в System.DateTime.DateToTicks(Int32, Int32, Int32)
   в StatisticsAnalysisTool.ViewModels.MainWindowViewModel+<SetUiElements>d__54.MoveNext()
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   в System.Windows.Threading.DispatcherOperation.InvokeImpl()
   в MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   в System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   в System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   в System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   в MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   в System.Windows.Threading.DispatcherOperation.Invoke()
   в System.Windows.Threading.Dispatcher.ProcessQueue()
   в System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   в MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   в System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   в MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   в System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   в System.Windows.Application.RunDispatcher(System.Object)
   в System.Windows.Application.RunInternal(System.Windows.Window)
   в StatisticsAnalysisTool.App.Main()

For this days i'm not update windows and not install new programs in my system. Reinstall app, install .NET 5.0, reboot computer - doesn't solve this problem. Have any ideas?

My system:

Windows 10 Pro
20H2
19042.685
Windows Feature Experience Pack 120.2212.551.0

![22-01-2021_20-04-59_tnq5g](https://user-images.githubusercontent.com/1575688/105521675-446e0e80-5ced-11eb-8374-236557940fbc.png)
![22-01-2021_20-04-40_i32ch](https://user-images.githubusercontent.com/1575688/105521679-4506a500-5ced-11eb-9ee3-8d5a4db95abc.png)
![22-01-2021_20-04-18_iw4ua](https://user-images.githubusercontent.com/1575688/105521682-459f3b80-5ced-11eb-96a4-6330321d5a71.png)

**Comment by Tiaryn** [comment]
It's showing the same errors for me.
The .NET Runtime installer for 4.8 says I can't install because it already is installed.

Error messages in english:

> 
> Application: StatisticsAnalysisTool.exe
> Framework Version: v4.0.30319
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.ArgumentOutOfRangeException
>    at System.DateTime.DateToTicks(Int32, Int32, Int32)
>    at StatisticsAnalysisTool.ViewModels.MainWindowViewModel+<InitMainWindowData>d__16.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
>    at System.Windows.Threading.DispatcherOperation.InvokeImpl()
>    at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
>    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
>    at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
>    at System.Windows.Threading.DispatcherOperation.Invoke()
>    at System.Windows.Threading.Dispatcher.ProcessQueue()
>    at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
>    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
>    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
>    at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG ByRef)
>    at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
>    at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
>    at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
>    at System.Windows.Forms.Form.ShowDialog(System.Windows.Forms.IWin32Window)
>    at AutoUpdaterDotNET.AutoUpdater.ShowUpdateForm()
>    at AutoUpdaterDotNET.AutoUpdater.BackgroundWorkerOnRunWorkerCompleted(System.Object, System.ComponentModel.RunWorkerCompletedEventArgs)
>    at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(System.ComponentModel.RunWorkerCompletedEventArgs)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
>    at System.Windows.Threading.DispatcherOperation.InvokeImpl()
>    at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
>    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
>    at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
>    at System.Windows.Threading.DispatcherOperation.Invoke()
>    at System.Windows.Threading.Dispatcher.ProcessQueue()
>    at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
>    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
>    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
>    at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
>    at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
>    at System.Windows.Application.RunDispatcher(System.Object)
>    at System.Windows.Application.RunInternal(System.Windows.Window)
>    at StatisticsAnalysisTool.App.Main()

> Faulting application name: StatisticsAnalysisTool.exe, version: 1.7.0.0, time stamp: 0x5e53d950
> Faulting module name: KERNELBASE.dll, version: 10.0.19041.662, time stamp: 0xec58f015
> Exception code: 0xe0434352
> Fault offset: 0x000000000002d759
> Faulting process id: 0x1028
> Faulting application start time: 0x01d6f1c5db4f75f3
> Faulting application path: D:\Dateien\Downloads\StatisticsAnalysis-AlbionOnline-v1.7.0\StatisticsAnalysisTool.exe
> Faulting module path: C:\Windows\System32\KERNELBASE.dll
> Report Id: af1d01bc-19da-4dc4-af1b-40aa9f24f6fd
> Faulting package full name: 
> Faulting package-relative application ID:
