### ISSUE TITLE
Save dungeons every few dungeons

### ISSUE THREAD

**Issue by GildedS** [Triky313/AlbionOnline-StatisticsAnalysis#160]
Been having an issue where if i don't close the tool properly,  it does not save the count of dungeons i've done that day. Can be triggered by shutting off the pc and letting Windows close the program.

Acceptance Criteria:
Every 3-5 dungeons, the dungeons are saved to the file.

**Comment by Triky313** [comment]
This can happen, you should always close the tool yourself.
When shutting down Windows, the saving of data cannot be guaranteed.

**Comment by GildedS** [comment]
> This can happen, you should always close the tool yourself. When shutting down Windows, the saving of data cannot be guaranteed.

is there a way for the tool to save the count on an hourly basis though, and instead of when i close the tool?

**Comment by Triky313** [comment]
I just implemented such a feature for mails today. I'll see that this works for dungeons too.
