### ISSUE TITLE
Silver pickup value is not being tracked in dungeons

### ISSUE THREAD

**Issue by GildedS** [Triky313/AlbionOnline-StatisticsAnalysis#162]
For the past few solo dungeons, the silver i pick up off the ground is not being tracked, attached below is a string of dungeons with this problem 
![OnPaste 20220808-153514](https://user-images.githubusercontent.com/75071007/183364913-52720a15-905d-4a66-9314-115da12e2b06.png)

**Comment by Triky313** [comment]
![image](https://user-images.githubusercontent.com/14247773/184110916-86173f2f-a509-43b0-8266-69fe763a4d9a.png)

So, I tested it and it shows the silver for me. What version is your tool?
@GildedS

**Comment by GildedS** [comment]
> ![image](https://user-images.githubusercontent.com/14247773/184110916-86173f2f-a509-43b0-8266-69fe763a4d9a.png)
> 
> So, I tested it and it shows the silver for me. What version is your tool? @GildedS

It seemed to be fixed from the latest version, during the time of the bug i was using a the last pre release before the latest update
