### ISSUE TITLE
Damage taken in the dps meter

### ISSUE THREAD

**Issue by Triky313** [Triky313/AlbionOnline-StatisticsAnalysis#164]
Show the damage a player taken

**Comment by Rt7777777o** [comment]
Is there a question about the DPS injury table here?

**Comment by Rt7777777o** [comment]
I have a question about the DPS table. May I ask if it's here?

**Comment by Rt7777777o** [comment]
Chinese:
我使用您的插件有两年的时间了,虽然它经常有小毛病,但是他是免费的公益性的,我非常喜欢.
我的dps数据表格在刚开始打开软件后的第一个地图有效,当我更换地图后,只显示我一个人的伤害数据,其他的人伤害数据不再显示,偶尔会在HCE进行到尾声时开始记录队友的伤害数据.

我的设备信息:
win11  22H2  22621.2715
Npcap 1.78
.NET 7.0.14
DNS 114.114.114.114   8.8.8.8

English:
I have been using your plugin for two years now, and although it occasionally has minor glitches, I truly appreciate its altruistic nature as a free tool. I am immensely fond of it.
Initially, my DPS data spreadsheet effectively recorded the damage data for all players upon opening the software. However, after switching to a different map, it only displays my own damage data, no longer showing the data for other players. Occasionally, towards the end of a High-End Content Encounter (HCE), it starts recording my teammates' damage data.

My device information:
win11  22H2  22621.2715
Npcap 1.78
.NET 7.0.14
DNS 114.114.114.114   8.8.8.8

**Comment by Rt7777777o** [comment]
Chinese:
我尝试过切换DNS和加速器,也重新安装过.NET的所有版本和Npcap.但是效果都不理想.这令我非常苦恼,我已经习惯观看dps输出数据来进行游戏,没有了它非常的难受.请问你有什么能够帮我的意见吗?

English:
I have tried switching DNS and using accelerators, as well as reinstalling all versions of .NET and Npcap. However, the results have been far from satisfactory. This has caused me great distress, as I have become accustomed to monitoring DPS output data while playing. It feels incredibly uncomfortable without it. May I ask if you have any suggestions that can help me?

**Comment by Rt7777777o** [comment]
Chinese:
我和朋友一人攻击了一下假人
English:
My friend and I attacked the dummy alone
![1](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/106268726/0726b90e-e3f4-4e2d-8a93-893ac57cb362)
![2](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/106268726/8ae749b3-8265-450b-9ea0-8abf82f0497c)

**Comment by Rt7777777o** [comment]
Chinese:
我可以提供Todesk远程控制
English:
I can provide Todesk remote control

**Comment by Rt7777777o** [comment]
Chinese:
即使我开了vpn也不可行
English:
Even if I open VPN, it's not feasible
![image](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/106268726/0c0005b9-6119-4514-87d5-a4ce777c2481)

**Comment by Triky313** [comment]
Do these problems only occur in HCEs?
There seems to be a problem with HCE's at the moment, but all other maps the damage meter should work normally.

**Comment by Rt7777777o** [comment]
This error occurs in towns, islands, and HCE, while other maps are temporarily unknown. I am not sure if it is due to my computer issue or my issue in China that caused this error. However, I have reinstalled the system, reinstalled Npcap and .net, as well as plugins and games, and this issue still exists

**Comment by Rt7777777o** [comment]
I can provide Totdesk remotely to help you check for errors, or I can assist you in any other way I can

**Comment by Triky313** [comment]
Added in https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/releases/tag/v7.7.1
