### ISSUE TITLE
Reset Dungeon tracking for the day

### ISSUE THREAD

**Issue by GildedS** [Triky313/AlbionOnline-StatisticsAnalysis#169]
Not sure what time does the program decides to reset the daily dungeon tracker, but it's not very accurate for most timers. So it'd be nice to be able to manually reset it

(I apologize for asking for so many dungeon related features)

**Comment by Triky313** [comment]
So I don't see any setting in my tool to reset tracked dungeons daily.
Can you describe your problem in more detail or describe what you would like to have as a feature?

**Comment by GildedS** [comment]
> So I don't see any setting in my tool to reset tracked dungeons daily. Can you describe your problem in more detail or describe what you would like to have as a feature?

It's like the Reset Dungeon Tracking button, But instead of resetting everything it just resets the count for dungeons of the day, as well as the data associated with it (Fame, Silver, Fame credits and so on). Everything underlined in red is what needs to be reset with this feature.

It'd be handy to have this feature so that people can accurately reset their fame tracking within dungeons.
![OnPaste 20220829-171622](https://user-images.githubusercontent.com/75071007/187167849-406580ad-8508-4aad-a51f-0fe257db89c0.png)

**Comment by Triky313** [comment]
Oh okay, that's what you mean, I see.
I'll take a look.
