### ISSUE TITLE
Mail monitoring search doesn't display "cedar planks"

### ISSUE THREAD

**Issue by ChirilRussu** [Triky313/AlbionOnline-StatisticsAnalysis#172]
**Describe the bug**
Mail monitoring search filter doesn't display "cedar planks"

**To Reproduce**
Launch the tool / Have mail monitoring turned on / "sell order" cedar planks at the market / open the notification mail about the transaction / note that the log of the transactions appeared in the full list of transactions / type "cedar" into the filter search bar / note that the planks don't appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/58755601/189253103-c8dcc257-dc49-4249-a778-8414df88f767.png)
![image](https://user-images.githubusercontent.com/58755601/189253130-210c178d-b8e5-4217-859f-b76d79682065.png)

**Expected behavior**
The filter displays cedar planks.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home, 64-bit
 - Tool Version: 5.12.1.21998
 - NPcap Version: 0.9983

**Comment by Triky313** [comment]
First of all you should update your NPcap version if possible! v0.9983 is very old.

![image](https://user-images.githubusercontent.com/14247773/189715444-b52bf8a8-6ad6-4259-8f22-d1fa2c3a32c8.png)

I haven't been able to find any problems so far, if something happens again, please open a new issue.
