### ISSUE TITLE
i am already download and use the Npcap  and it also be  Tracking is partially active(please change the zone)

### ISSUE THREAD

**Issue by JinYanyaaa** [Triky313/AlbionOnline-StatisticsAnalysis#173]
![image](https://user-images.githubusercontent.com/113360054/189665959-e4908ffc-afc1-48fb-995b-bdeda3613b6c.png)

**Comment by Triky313** [comment]
Please update your tool, the version is out of date!

**Comment by JinYanyaaa** [comment]
over
