### ISSUE TITLE
i am already download and use the Npcap and it also be Tracking is partially active(please change the zone) 

### ISSUE THREAD

**Issue by JinYanyaaa** [Triky313/AlbionOnline-StatisticsAnalysis#174]
![image](https://user-images.githubusercontent.com/113360054/189942731-6959e7c9-2865-4db7-99be-6071615e912d.png)
Updated to the latest version with built-in updates
the same with problem #173

**Comment by JinYanyaaa** [comment]
over

**Comment by Triky313** [comment]
Do you use a VPN (e.g. ExitLag)?
Have you changed the map in game?
Are you using GeForce NOW?
