### ISSUE TITLE
Mail monitoring / search filter completely stopped working.

### ISSUE THREAD

**Issue by ChirilRussu** [Triky313/AlbionOnline-StatisticsAnalysis#175]
**Describe the bug**
Opening mail stopped logging transactions completely. (mail monitoring is active),

Typing ANY item names into the search / filter bar has no effect. 
Mousing over the item list and scrolling the mouse wheel makes the item list disappear.

**To Reproduce**
Select mail monitoring / type granite into search bar / observe nothing happens.
Hover the item list / scroll wheel up or down / observe the list disappeared.

**Screenshots**
https://www.youtube.com/watch?v=ku9kdtBVU2g

**Desktop (please complete the following information):**
    OS: Windows 10 Home, 64-bit
    Tool Version: 5.12.1.21998
    NPcap Version: 1.71

**Additional context**
Previous thread https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/issues/172 
I reinstalled / updated NPcap, reinstalled the tool, restarted PC.

**Comment by Triky313** [comment]
Pleas update the tool to the latest pre-release v5.13.0

If you activate this option in the settings, you can download the update directly:
![image](https://user-images.githubusercontent.com/14247773/190492209-9c0725e9-2f60-4a1c-a241-eca9e8cfbe2b.png)

**Comment by ChirilRussu** [comment]
That helped, thanks = )
