### ISSUE TITLE
Not logging pvp kills correctly in Corrupted

### ISSUE THREAD

**Issue by mugaur689** [Triky313/AlbionOnline-StatisticsAnalysis#176]
Hi I found that the pvp kill/death count logger is not working while in a corrupted.  It's seems to log some of the deaths but not kills.  All other aspects of the app work great!

**Comment by Triky313** [comment]
I would have to test it, if possible, please make a video of it!

**Comment by Triky313** [comment]
Kills are currently not reflected in the dungeon overview for Corrupted Dungeons. This could be in a future feature.
