### ISSUE TITLE
Storage History remains blank

### ISSUE THREAD

**Issue by Gaffigoo** [Triky313/AlbionOnline-StatisticsAnalysis#180]
**Describe the bug**
Tool seems to be actively tracking and most all features working correctly. When I open a new bank I see the bank added to the drop down menu near the top of the "Storage History" tab.  Nothing else populates. 

**To Reproduce**
1. Open analysis tool
2. Open Albion
3. Walk into market bank of any city
4. Open bank

**Expected behavior**
Items should be logged and displayed in the "Storage History" section

![storagescreen](https://user-images.githubusercontent.com/90939479/194753202-70640fe0-c7bb-4423-b335-f766bc4878f6.PNG)

**Comment by Triky313** [comment]
Update the tool please.

**Comment by gabrahan** [comment]
I am having the same problem and the tool is completely updated and all the possible problem fixes are done.. still blank.
![image](https://user-images.githubusercontent.com/82899537/194780823-9f472e61-c168-46c3-8e39-9516e480d834.png)

**Comment by Gaffigoo** [comment]
So this was actually resolved by checking the "Suggest pre-release updates" and hitting save before using the update button. 

If you're on 5.13 now upgrading to 5.14 seems to work

**Comment by gabrahan** [comment]
> So this was actually resolved by checking the "Suggest pre-release updates" and hitting save before using the update button.
> 
> If you're on 5.13 now upgrading to 5.14 seems to work

Done and fixed, thank you very much kind sir. Have a good day!
