### ISSUE TITLE
Can not save the damage snapshots when pass the map

### ISSUE THREAD

**Issue by Stuart0905** [Triky313/AlbionOnline-StatisticsAnalysis#184]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Tool Version [e.g. 5.0.0]
 - NPcap Version [e.g. 1.6]
![image](https://user-images.githubusercontent.com/40737218/197290873-54094b83-b106-4b9f-a723-a6c88ee9e57f.png)

**Additional context**

**Comment by Triky313** [comment]
Please update the tool to the newest version!
