### ISSUE TITLE
Cant open application

### ISSUE THREAD

**Issue by derd1234** [Triky313/AlbionOnline-StatisticsAnalysis#185]
**Describe the bug**
Opening StatisticsAnalysisTool does nothing.
I have both runtime and npcap installed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Tool Version 5.14.2
 - NPcap Version 1.71

**Comment by Triky313** [comment]
"Can't open application" and "Opening Statistics Analysis Tool does nothing" are 2 different problems, what exactly isn't working now?

If you are using a VPN e.g. ExitLag then this will not work, please disable it.

**Comment by derd1234** [comment]
Double clicking StatisticsAnalysisTool doesnt open anything. Nothing happens....

**Comment by Triky313** [comment]
How are your PC specs?

**Comment by kaiaky** [comment]
i have same problem after update. I click on .exe and do nothing. Dont launch the program and dont make any error message

**Comment by compinerd** [comment]
still have the same problem since months, very sad
