### ISSUE TITLE
Can't load

### ISSUE THREAD

**Issue by ImAsasin22** [Triky313/AlbionOnline-StatisticsAnalysis#191]
**Describe the bug**
So, I wanted to check the prices, and double clicked app, something started loading and stopped. Nothing happened. 

**To Reproduce**
1. I opened folder with your app
2. I double clicked your app
3. Something started loading (that blue circle next to cursor)
4. App doesn't start

**Expected behavior**
Usually after loading, the windows shows up and I can use it.
**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://user-images.githubusercontent.com/117238044/199364707-c7b2fbe9-aabc-4bc1-bff4-1fd67aaf5134.mp4)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Tool Version [e.g. 5.0.0]: StatisticsAnalysis-AlbionOnline-v5.14.2-x64
 - NPcap Version [e.g. 1.6]: I think it is 1.71, but idk how to check that

**Additional context**
If u could, please anwser fast

**Comment by Triky313** [comment]
Hay @ImAsasin22 
Please install .net 6 runtime desktop: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.5-windows-x64-installer

**Comment by ImAsasin22** [comment]
It works! Thank You :)!
