### ISSUE TITLE
Search feature not working in Mail Monitoring

### ISSUE THREAD

**Issue by zekhaliro** [Triky313/AlbionOnline-StatisticsAnalysis#194]
Search feature not working after i have 490 mail, when i input keyword then it doesn't show anything, and i hope in future update Mail Monitoring can import/export to excel/google sheets.

**Comment by Triky313** [comment]
I have over 6000 mails and it works without problems.

What version of the tool do you have?
Is there anything in the log file in the tool folder?

**Comment by zekhaliro** [comment]
v5.14.2 cuz doesnt work then i try update but still doesnt.

Is there anything in the log file in the tool folder?
Idk, just this maybe u can check.
[StatisticsAnalysisTool.log](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/files/9960548/StatisticsAnalysisTool.log)

**Comment by zekhaliro** [comment]
Ok thank you.

**Comment by Triky313** [comment]
I can't reproduce it.
Yes, the search is very slow and I'm working on a better solution, but it basically works.

Type something and wait a few seconds.

If you have further problems, please write exactly what you are entering.
