### ISSUE TITLE
This moved to param '10' now fyi

### ISSUE THREAD

**Issue by zenion** [Triky313/AlbionOnline-StatisticsAnalysis#199]
https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/blob/6727169880dd08c94f42f21d24819aeaffaa3745/src/StatisticsAnalysisTool/Network/Events/UpdateFameEvent.cs#L66

**Comment by zenion** [comment]
PR @ https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/pull/200 for mists release

**Comment by Triky313** [comment]
As soon as I can log back into the test server, I'll take a look and merge your pull request. Thanks.
