### ISSUE TITLE
Translate dont work

### ISSUE THREAD

**Issue by ValkaL** [Triky313/AlbionOnline-StatisticsAnalysis#2]
Language - Russian
Written in search box and not have results.
If change to ENG lang - all okay.
![09-02-2020_18-04-12_tbkz0](https://user-images.githubusercontent.com/1575688/74104526-ab3efa00-4b66-11ea-8a0f-5d4c947aebe8.png)

**Comment by Triky313** [comment]
Thanks for reporting.
Fixed in [Version 1.5.1](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/releases/tag/1.5.1)
