### ISSUE TITLE
lootlogger show wrong items

### ISSUE THREAD

**Issue by madvac** [Triky313/AlbionOnline-StatisticsAnalysis#203]
hi,

loot-logger writing wrong items in csv file.

For example: if i loot "trash" logger show "facebreaker"

Thanks.

**Comment by Triky313** [comment]
It is possible that many new items are not yet displayed or that incorrect items are displayed in the storage history. Therefore, please make sure that your item list is up to date. Usually these are updated very quickly (https://github.com/broderickhyman/ao-bin-dumps). 

If this is not the case, please switch to the following links:
https://raw.githubusercontent.com/Triky313/ao-bin-dumps/main/formatted/items.json
https://raw.githubusercontent.com/Triky313/ao-bin-dumps/main/items.json

You can easily replace or save them in the settings.
Then please delete the ItemList.json and Items.json files from the tool folder and restart the tool.
![image](https://user-images.githubusercontent.com/14247773/203787070-e7a15e9e-acd0-449b-9612-d56f87d9332e.png)

![image](https://user-images.githubusercontent.com/14247773/203787086-cca3ba10-bccb-4151-b4e8-3c1205177a84.png)

**Comment by madvac** [comment]
i think it is fixed..i have old json files...thx for help.
