### ISSUE TITLE
A Suggestion About Number Unit

### ISSUE THREAD

**Issue by Me1onSeed** [Triky313/AlbionOnline-StatisticsAnalysis#212]
Could you please transform those number to units, like those in game. 
It might be simple to recognize them. 
For example: 1,634,246  →  1.63 m

**Comment by Triky313** [comment]
In which area?
This already happens in many places, but it is not useful everywhere.

**Comment by Me1onSeed** [comment]
Fame, sliver and respec in 
[Dashboard], Dungeon Stats in [Dungeons], [Player Information]
