### ISSUE TITLE
Dungeons feature not working

### ISSUE THREAD

**Issue by SimonasJa** [Triky313/AlbionOnline-StatisticsAnalysis#213]
**Describe the bug**
Dungeons list does not show new dungeons.

**To Reproduce**
Not sure exactly since I can't get feature to work anymore.

**Expected behavior**
Dungeon list populated with data from `DungeonRuns.json`.

**Screenshots**
You can see I'm in a dungeon, but list is empty.
![image](https://user-images.githubusercontent.com/47528686/212386432-8fb9fff8-75f2-4888-870e-d4eed037d33b.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Tool Version 5.15.6
 - NPcap Version 1.72

**Additional context**
This feature used to work till something happened, last completed dungeon was 5.3 Group Dungeon, after that no new dungeon would appear in the list even though I can see `DungeonRuns.json` is being updated with correct information.
Whenever I enter new dungeon the list flashes for a split second and disappears. Tried reinstalling this tool and npcap.

**Comment by kolik151** [comment]
doesn't work for me too
