### ISSUE TITLE
Lootlogger

### ISSUE THREAD

**Issue by Triky313** [Triky313/AlbionOnline-StatisticsAnalysis#22]

**Comment by sh1ny** [comment]
Hey,

I am really interested in reliable loot logger, do we have any ETA on this ? Also what would help you prioritize this ?

**Comment by Triky313** [comment]
Hay,
I have actually already prepared the first steps for the lootlogger. At the moment, i first have to fix a few minor errors in the Damage Meter, then I will start adding the lootlogger as soon as possible.
