### ISSUE TITLE
Double loot at "Storage History"

### ISSUE THREAD

**Issue by SlowKingg** [Triky313/AlbionOnline-StatisticsAnalysis#227]
There is double loot because for example it's checks in Bank of Thetford and Thetford Portal but it's same loot. 

![image](https://user-images.githubusercontent.com/36215040/216294059-3084d141-2e42-43a2-8088-04d07a1a8a2c.png)

**Comment by Triky313** [comment]
A similar feature will be available directly in Albion soon, which is why I will not develop this feature further for the time being.
