### ISSUE TITLE
Wont start

### ISSUE THREAD

**Issue by LeventeBuda** [Triky313/AlbionOnline-StatisticsAnalysis#228]
The app wont start after the I updated it. 

I use win 10 (10.0.19044 build 19044).

I tried to reinstall it and it did not helped.

**Comment by LeventeBuda** [comment]
If I dont update the tool I can use it. 
Plus I just updated my windows so its the newest version now.

**Comment by Triky313** [comment]
What tool version do you use?

**Comment by LeventeBuda** [comment]
I freshly downloaded the app and updated it when it requested it.

**Comment by LeventeBuda** [comment]
But the version is v5.14.2.875

**Comment by Triky313** [comment]
Please update the tool https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/releases/download/v5.15.8/StatisticsAnalysis-AlbionOnline-v5.15.8-x64.zip

**Comment by LeventeBuda** [comment]
It wont start.

**Comment by Triky313** [comment]
Please start completely in a new folder without old files. NPcap and .net 6.0 installed?

**Comment by LeventeBuda** [comment]
I used the tool before so they are installed, but I will reainstall them

**Comment by LeventeBuda** [comment]
I reinstalled the .net and NPcap and I think the NPcap was too old. It was 1.6 and the newest is 1.72. Thank you for the help!
