### ISSUE TITLE
Statistics per dungeon

### ISSUE THREAD

**Issue by emil-nasso** [Triky313/AlbionOnline-StatisticsAnalysis#23]
I LOVE the new tracking feature, very nice work. :) 

I would like to request one feature though. Statistics per dungeon.

Right now, we can see fame/h, famecredits/h and silver/h in total in the upper part of the screen.

It would be amazing if we could see the same statistics, per dungeon. Fame per dungone and duration is already shown, so I think it is tracked, but just not calculated per hour and displayed in the UI?

Enjoy my mspaint mockup. ;) 

![image](https://user-images.githubusercontent.com/1119706/107682245-60d3ea00-6ca0-11eb-950f-b0b542e5b4f3.png)

Keep up the good work. Amazing app so far!

**Comment by Triky313** [comment]
Hay you,
I already have the idea in my head. I can implement that.
Unfortunately, the PvE and PvP Fame is currently indistinguishable, I hope I'll find a solution soon. But your feature idea will come. :)

**Comment by emil-nasso** [comment]
Great. :)

Pvp and pve fame being indistinguishable sounds tricky. Maybe you can see kills and then ignore the fame that comes before/after that? :P 

That would might only work when you get the final blow though?

It would still be great, even if pvp fame was included in the tracked fame. I don't think that many people will run this when they pvp. :) even if you get dove in a dungeon and manage to defend yourself and mess up the tracking of that dungeon, it doesn't seem like a big issue.
