### ISSUE TITLE
Tracking problem

### ISSUE THREAD

**Issue by Nizelan** [Triky313/AlbionOnline-StatisticsAnalysis#233]
**Describe the bug**

**To Reproduce**
1. Login game
2. Start [AlbionOnline-StatisticsAnalysis]

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Wind]
 - Tool Version [e.g. 5.16.0.31245]
 - NPcap Version [e.g. 1.6]

**Additional context**
can't track damage
can't any data for party or something else

**Comment by Triky313** [comment]
Do you use VPN like ExitLag or Geforce NOW?

**Comment by Nizelan** [comment]
No

**Comment by Nizelan** [comment]
Use old version solve my problem

**Comment by Triky313** [comment]
What Windows do you use?

**Comment by Nizelan** [comment]
"Windows 10 Version 22H2 for x64-based Systems"

**Comment by Triky313** [comment]
Please reinstall NPcap and .net 6.0 desktop and try it again.
Also we have a new update after this days Albion Online server downtime.

**Comment by Nizelan** [comment]
Its just stop working after update and fix after i load new version of app. 
I think you rolled out the update to your program too quickly -_-
