### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Ruballion** [Triky313/AlbionOnline-StatisticsAnalysis#237]
**Describe the bug**
I follow the instructions but program is still now working could you help me ?

**Comment by Triky313** [comment]
What exactly isn't working?

I need more information my friend!
What windows do you use and what version of the tool do you use?

**Comment by Ruballion** [comment]
Hi Aaron, the program cant catch my fame or any dps that i do. So
basically not working i am using windows 10 and it was working before
Albion's last patch like couple days ago. Could you help me about this?


Aaron Schultz ***@***.***>, 16 Şub 2023 Per, 11:03 tarihinde
şunu yazdı:

**Comment by Triky313** [comment]
You need to update the tool to the newest version 5.17.0

**Comment by Ruballion** [comment]
I tried 5.17.0 version and its working thanks a lot mate
