### ISSUE TITLE
mobs.json cant not be downloaded (v5.17.0)

### ISSUE THREAD

**Issue by Grabthatcrack** [Triky313/AlbionOnline-StatisticsAnalysis#240]

**Comment by AidGames121212** [comment]
> In the project folder there is a file called DownloadItemJsonFilesManually.bat, please start it and then start the tool again.

When DownloadItemJsonFilesManually.bat started downloading mobs,json - it crashes. What can i do?

**Comment by Triky313** [comment]
This is a console application, this should not happen. This seems to be a problem on your computer. Do you have admin rights on your computer? Which Windows are you using?

**Comment by AidGames121212** [comment]
Win10, have admin rights. I find mobs.json on github.com/broderickhyman/ao-bin-dumps but i cannot paste it in right folder, program need to download it from this resource...

**Comment by shannon-33** [comment]
I also encountered the same problem. After I logged off mobs by various means, there was a situation that mobs would be automatically deleted

**Comment by shannon-33** [comment]
I also encountered the same problem, using a variety of means, will automatically delete

**Comment by shannon-33** [comment]
I also encountered the same problem, tried a variety of ways to download, will automatically delete

**Comment by Triky313** [comment]
I've released a new version that shows the downloading of the files better and fixes a bug.
https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/releases/tag/v5.17.2
