### ISSUE TITLE
I found that the mobs.json file will be deleted by start the .exe

### ISSUE THREAD

**Issue by liuboyan12** [Triky313/AlbionOnline-StatisticsAnalysis#252]
Hi bro, I have a stupid question, I found the mobs.json file from my friend and save the file at the root path, to solve the problem when started the .exe ...(mobs.json file lost) but when I click the .exe I found that the mobs.json file was deleted in auto... So do I forget something?

**Comment by Triky313** [comment]
It is normal for the file to be deleted. It ends up modified in another folder.

**Comment by Dunaidi** [comment]
Hi,bro,i run the DownloadItemJsonFilesManually.bat ,but it crash when download the mobs.json, i try different way to solve this problem,but i fail.

**Comment by Triky313** [comment]
@Dunaidi 
Download the latest version and make sure you have admin rights on the PC. You must have permission to create folders and files.
