### ISSUE TITLE
tracking is partially active(please change the zone!)

### ISSUE THREAD

**Issue by foolstuck** [Triky313/AlbionOnline-StatisticsAnalysis#259]
Does this app work for albion east?

And how do I fix the issue as the title states?

**Comment by Triky313** [comment]
East Server update is coming in a few minutes.
You have to change the map once ingame for all functions of the tool to work.

**Comment by for-mat** [comment]
> 
I've switched the map around a few times, but it still says "UNKNOWNSERVER tracking is partially active", and I can't even search for player information on Asia Server

**Comment by Boreas813** [comment]
I had the same issue

**Comment by Boreas813** [comment]
I know what's going on, China GFW is blocking something. App worked fine when I setup a global proxy in Singapore. Maybe you can teach us to locate which network request failed, and we'll figure it out.

**Comment by Triky313** [comment]
Do you all have the latest version of the tool? 
So v5.18.1?

**Comment by for-mat** [comment]
> Do you all have the latest version of the tool? So v5.18.1?

Yes, I'm using v5.18.1
I found that when looking up player information, I could find the West server user, but not the East server user
Could you please tell me the address of the queried interface? I want to verify whether there is a network problem

**Comment by for-mat** [comment]
> I know what's going on, China GFW is blocking something. App worked fine when I setup a global proxy in Singapore. Maybe you can teach us to locate which network request failed, and we'll figure it out.

兄弟你能用吗，我开了vpn还是显示tracking is partially active(please change the zone!)

**Comment by Triky313** [comment]
WEST
https://albion-online-data.com/api/swagger/index.html

EAST
https://east.albion-online-data.com/api/swagger/index.html

**Comment by Boreas813** [comment]
> > I know what's going on, China GFW is blocking something. App worked fine when I setup a global proxy in Singapore. Maybe you can teach us to locate which network request failed, and we'll figure it out.
> 
> 兄弟你能用吗，我开了vpn还是显示tracking is partially active(please change the zone!)



> > I know what's going on, China GFW is blocking something. App worked fine when I setup a global proxy in Singapore. Maybe you can teach us to locate which network request failed, and we'll figure it out.
> 
> 兄弟你能用吗，我开了vpn还是显示tracking is partially active(please change the zone!)

可以，要挂全局代理，用sstap挂一个新加坡节点就好了
