### ISSUE TITLE
Is it possible to add fishing to the gathering tracker?

### ISSUE THREAD

**Issue by LeventeBuda** [Triky313/AlbionOnline-StatisticsAnalysis#264]
It is not related to an issue. But I do fishing and it would be great if fishing would be added to the gathering tracker

**Comment by Triky313** [comment]
Added in [v6.1.0](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/releases/tag/v6.1.0) dc5b1476c8544ecbec3d0378cc97a583f1b015bb
