### ISSUE TITLE
mobs.json!!!!

### ISSUE THREAD

**Issue by JinYanyaaa** [Triky313/AlbionOnline-StatisticsAnalysis#272]
cant get the file mobs.json!

**Comment by Triky313** [comment]
More information please!
What is happening?

**Comment by JinYanyaaa** [comment]
The software cannot automatically obtain mobs.json;

Running DownloadItemJsonFilesManually. bat reports an error, indicating that the connection has been closed

**Comment by Triky313** [comment]
Please make sure you are not using a VPN, and you must have full access to your computer, no protected folders.

**Comment by kkkingim** [comment]
Try download it from your browser, and put it under Temp folder manually

**Comment by JinYanyaaa** [comment]
已解决，谢谢各位

**Comment by mckenna654** [comment]
Getting this also. Have tried everything under the sun to get it working!

**Comment by mckenna654** [comment]
> More information please! What is happening?

mobs.json cannot be loaded

**Comment by Triky313** [comment]
Please download the latest version of the tool and try again. 
https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/releases/tag/v5.18.2
