### ISSUE TITLE
Manually select game servers in settings

### ISSUE THREAD

**Issue by Jerome-yale** [Triky313/AlbionOnline-StatisticsAnalysis#276]
I am an Eastern server player, how to make the value of Eastern server items displayed by default. Can tools differentiate between East and West servers without logging into the game?
It would be a great help if that could be done

**Comment by Triky313** [comment]
Thanks for the feedback, I hadn't even thought of that.

**Comment by Triky313** [comment]
Implemented in v5.19.0
