### ISSUE TITLE
Software crashing PC

### ISSUE THREAD

**Issue by askhenrique2** [Triky313/AlbionOnline-StatisticsAnalysis#287]
Softwares works ok, but after about 30 min the software crashes and nothing on the computer works for about 1 minute. Usualy I have to open and close everything again: Tracking tool, Albion, and Discord. A few friends having the same issue. Im on Windows 11.

**Comment by Capivara-Polar** [comment]
I also have the same problem, but in my case I'm using win 10

**Comment by Triky313** [comment]
This is absolutely new to me. 
In the latest version, please set the Network Filtering to active in the settings so that as little data as possible is read, maybe that will help.

**Comment by askhenrique2** [comment]
Ill teste later today. Seems as it can be a solution, since we are from Brazil

**Comment by askhenrique2** [comment]
Worked perfectly for me, ty Trinky313

**Comment by King-May** [comment]
`ERROR 2023-05-04 00:02:20 - [32] message:Device_OnPacketArrival 
 method:Device_OnPacketArrival 
 stacktrace:SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch > SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch > SharpPcap.LibPcap.PcapDevice.PacketHandler > SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent > StatisticsAnalysisTool.Network.NetworkManager.Device_OnPacketArrival 
 line: 208 
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at PhotonPackageParser.PhotonParser.HandleSendReliable(Byte[] source, Int32& offset, Int32& commandLength)
   at PhotonPackageParser.PhotonParser.HandleCommand(Byte[] source, Int32& offset)
   at PhotonPackageParser.PhotonParser.ReceivePacket(Byte[] payload)
   at StatisticsAnalysisTool.Network.NetworkManager.Device_OnPacketArrival(Object sender, PacketCapture e) in D:\a\AlbionOnline-StatisticsAnalysis\AlbionOnline-StatisticsAnalysis\src\StatisticsAnalysisTool\Network\NetworkManager.cs:line 232`

**Comment by Capivara-Polar** [comment]
my problem is solved, thanks for the help my friend

**Comment by Mathieusu** [comment]
Same is happening to me. This is the first time I've tried the tracker and i've meet this issue. It runs fine but randomly it makes everything on the pc just explode. My Opera browser suddenly doesnt load any pages anymore and in some pages it shows the not enough memory error, crashes Albion, Discord and Steam. Looked up on task manager and pc resources were fine. Gpu, cpu, disk usage and ram were all on regular usage. Weirdly enough, my computer made some beeps as soon as this happened. Software beeps, not the beeps from the MOBO xd. Don't know if those beeps are from the tracker though, never heard them before. I'am also from Brazil, will try the network filtering option to see if it helps.

**Comment by jytcse** [comment]
I also have the same problem, if I use version 5.19 it will crash
but v5.18 is totally fine.

**Comment by Triky313** [comment]
Please set Network Filtering to active!

**Comment by Mathieusu** [comment]
Setting Network Filtering to active completely fixes the problem

**Comment by Triky313** [comment]
Fixed in https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/releases/tag/v5.21.0
