### ISSUE TITLE
Item Images are missing

### ISSUE THREAD

**Issue by RideMyPants** [Triky313/AlbionOnline-StatisticsAnalysis#3]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser - Chrome
 - Version - 2.0.2.32973

**Additional context**

**Comment by Triky313** [comment]
I am working on a solution.

**Comment by Triky313** [comment]
Fix in https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/releases/tag/2.1.0
