### ISSUE TITLE
Damage meter showing wrong weapons.

### ISSUE THREAD

**Issue by sh1ny** [Triky313/AlbionOnline-StatisticsAnalysis#30]
**Describe the bug**
Damage Meter is showing wrong weapons sometimes. Noticed in our avalonian we had enigmatic as top DPS. The guy wasn't even running enigmatic.

None of the weapons matched.

**To Reproduce**
1. Go to Tracking
2. Click on Damage Meter
3. Look at the stats
4. Weapons aren't accurate

**Expected behavior**

**Screenshots**

https://i.imgur.com/BFGPuR7.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: irrelevant ?!
 - Version: Version visible in the screenshot

**Additional context**
Not sure what caused this. We were running an flat 7 ava map. Dungeon/Fame tracking was working fine.

**Comment by Triky313** [comment]
This is probably because the recently added item list is not yet perfect. I look at this. Thanks for reporting.
