### ISSUE TITLE
Unable to filter data in trade monitoring tab

### ISSUE THREAD

**Issue by karigon** [Triky313/AlbionOnline-StatisticsAnalysis#309]
The "filter" feature on the trade monitoring tab is not working as intended. 

Unable to search for the correct item and will default to listing all items on record, from the oldest date to the newest date. I think this happened after the recent updates (unsure of which exactly), as I have not used it for a long time but it was working before.

**Comment by Triky313** [comment]
What version is your tool now?

**Comment by karigon** [comment]
> What version is your tool now?

I am using the latest version, v5.21

**Comment by Triky313** [comment]
I tested the whole thing. It's actually not optimal, but it can work if you play with the search a little. For example, write Royal and remove the l and write it down again.
I have to optimize it a little bit.
