### ISSUE TITLE
No Matches found ?

### ISSUE THREAD

**Issue by Ravenouski** [Triky313/AlbionOnline-StatisticsAnalysis#315]
someone know how to fix that? i have recorded a ganking session, selected all the loot in the filter and the party, but none is displaying 
![image](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/135903840/c7b497a9-a5d6-43c8-8ed6-892e13c5b3a3)

**Comment by Triky313** [comment]
Upload file content here please!

**Comment by madvac** [comment]
hi
problem is this line in csv file:
2023-06-09T22:29:34.3935638Z;;V I B I N;Markatos;SKIN_DIREWOLF_GVGSEASON_1ST_02;SKIN_DIREWOLF_GVGSEASON_1ST_02;6;;Golden Dollars;0NiNjA0P

i thing its wrong "name", it can be "Guild Season 2nd Place"

9133: SKIN_DIREWOLF_GVGSEASON_2ND_01                                   : Guild Season 2nd Place

**Comment by Triky313** [comment]
Yep, update itemlists in the tool please.
Delete the old itemlist.json and items.json from your tool directory.

**Comment by Ravenouski** [comment]
ty guys i have fixed the problem!
