### ISSUE TITLE
When trying to update the software, a System.Net.WebException is raised.

### ISSUE THREAD

**Issue by V1AraujoR1** [Triky313/AlbionOnline-StatisticsAnalysis#320]
When I open the software and an update is available, there is a message displayed - asking if I would like to download it. When the "Update" option is chosen, a small window with the software update shows up, to display the progress. However, before any progress is presented, a System.Net.WebException is raised with the message "An exception occurred during a WebClient request."

To reproduce it the way I did it is to simply try to use the update functionality. However, if there are more requirements for the bug to happen, such as system requirements, I wouldn't know.

I expected the update to genuinely happen, smoothly and successfully.
Please check the following image for more information:
![image](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/62629233/eb17e851-cfb2-4c54-a63f-30a65c6dcee8)

My operating system is Windows 10. The tool version is, as shown in the image, 5.21.2.24105. NPcap's version is 1.75.

If there is anything that is needed to know to fix this and I didn't provide, please ask for it and I will bring the information.

**Comment by Triky313** [comment]
I have now added a check that checks if the update URLs are available. If this is not the case, no update window will appear. This error can come for various reasons, in a pinch you can download the tool manually and overwrite the files in the old folder.

**Comment by Triky313** [comment]
8a81344c420958dcb32d98b7c3d7c0e489eb41ea
