### ISSUE TITLE
Wrong item detection for cyrillic (probably) client

### ISSUE THREAD

**Issue by Bikbai** [Triky313/AlbionOnline-StatisticsAnalysis#322]
Loot logger, storage history and gathering history shows wrong items.

Trade history tracker works well.

![image](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/68644428/c3e9a064-8180-471b-a104-904d6c75b818)

**Comment by Triky313** [comment]
Update itemlist.json and items.json please

**Comment by Bikbai** [comment]
> Update itemlist.json and items.json please

already did, no effect :(

![image](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/68644428/513cdcc6-1b9a-4bf8-8d62-a3368da900df)

**Comment by Triky313** [comment]
Please delete the city entries in the tool and try it again. I can not find a problem with the newest item lists.

**Comment by Bikbai** [comment]
> Please delete the city entries in the tool and try it again. I can not find a problem with the newest item lists.

Trade monitor works nicely, very strange situation.

Same problem also with loot logging and gather tracking - nothing to clear there.

here i've gathered rough stone inside hideout:

![image](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/68644428/ccaa376b-d2d0-4d9b-b79c-eac8dc23d9fa)

**Comment by Triky313** [comment]
Monitoring works without the item lists.
Gathering, damage meter and loot logger need the item lists. I don't see any problems there, I just updated the files again. It is best to delete the two files again and start the tool again.

**Comment by Bikbai** [comment]
Deleted, restarted and no effect :(
![image](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/68644428/d2f54d94-9200-4a64-a757-ad5b31617ef2)
![image](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/68644428/c123238c-ee60-4cc5-b40a-8dff47846e3e)

**Comment by Bikbai** [comment]
Not sure that its relates to subject
```
ERROR 2023-07-05 18:36:05 - [35] message:StatisticsAnalysisTool.Models.BindingModel.GatheringBindings+<<UpdateStatsAsync>b__12_0>d 
 method:MoveNext 
 stacktrace:System.Threading.Thread.StartCallback > System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart > System.Threading.ThreadPoolWorkQueue.Dispatch > System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext > System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop > StatisticsAnalysisTool.Models.BindingModel.GatheringBindings+<<UpdateStatsAsync>b__12_0>d.MoveNext 
 line: 114 
System.NullReferenceException: Object reference not set to an instance of an object.
   at StatisticsAnalysisTool.Models.BindingModel.GatheringBindings.<UpdateStatsAsync>b__12_6(Gathered x) in D:\a\AlbionOnline-StatisticsAnalysis\AlbionOnline-StatisticsAnalysis\src\StatisticsAnalysisTool\Models\BindingModel\GatheringBindings.cs:line 116
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`2.GetEnumerator()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.MaxBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IComparer`1 comparer)
   at StatisticsAnalysisTool.Models.BindingModel.GatheringBindings.<UpdateStatsAsync>b__12_0() in D:\a\AlbionOnline-StatisticsAnalysis\AlbionOnline-StatisticsAnalysis\src\StatisticsAnalysisTool\Models\BindingModel\GatheringBindings.cs:line 192
```

**Comment by Triky313** [comment]
I fixed this last bug but on what server are you online west or east?

**Comment by Bikbai** [comment]
West server, current state - not working :(

<img width="913" alt="image" src="https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/68644428/e4ce95ee-c46f-47f8-b3b3-f216151a06ed">

**Comment by Bikbai** [comment]
I cannot execute project from scratch, so cannot debug :(
