### ISSUE TITLE
Session statistics

### ISSUE THREAD

**Issue by arabinos** [Triky313/AlbionOnline-StatisticsAnalysis#323]
Introduction of changing the view of session statistics as in the image below. So that the player is not forced to use this tab just because he can check the statistics there. Which for me is not legible and too much stretched by the mass of information contained therein.

![dsadas](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/115917138/82e8471a-61e5-45e7-885c-2b8ff6fc1164)

**Comment by arabinos** [comment]
So I had an idea, I don't know if it's possible or not. If we repair an item where we have this statistic, it could be added automatically to the trade tabs, where we have buy/sell, add the repair parameter. So that we have our expenses and revenues in full, I know that you can add it manually, but if it is an automatic counting, wouldn't it be possible to add a parameter that would add something like that to the trade tab?

**Comment by Triky313** [comment]
Done in 67c37d500d4082ffd8ae9322b13544df423a1854
