### ISSUE TITLE
Damage meter not tracking properly

### ISSUE THREAD

**Issue by Lightcram** [Triky313/AlbionOnline-StatisticsAnalysis#328]
**Describe the bug**
After the last patch, my damage meter has not been capturing either any damage in my party or would not track numbers accurately. This happens even after restarting both the game and the tool, as well as resetting parties. I've reinstalled the tool too.

**To Reproduce**
1. Open albion statistic tool
2. Launch albion game
3. create party
4. check the damage meter tab of the tool

**Expected behavior**
Prior latest patch, damage meter tracks numbers accurately within the party

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Tool Version: 5.21.5.24201

 - NPcap Version: 1.73

**Comment by Triky313** [comment]
Update the tool to 5.21.8 pre-release and try it again
