### ISSUE TITLE
any way to make this work for mac m1?

### ISSUE THREAD

**Issue by satoshi0770** [Triky313/AlbionOnline-StatisticsAnalysis#329]
is there a way to make this work for mac m1?
anyway to build it myself for mac m1?
thanks

**Comment by Triky313** [comment]
Not at the moment, the tool would have to be completely redeveloped for this, the issue https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/issues/96 for this already exists but has not been dealt with much yet because it is a very large effort.
