### ISSUE TITLE
Dungeon Tier Offset

### ISSUE THREAD

**Issue by Faeeth** [Triky313/AlbionOnline-StatisticsAnalysis#350]
In the Dungeons tab, there is an offset with the tier of the completed dungeon.

### For example :
A real **T8.1** tier dungeon will be written **T8.0**
A real **T8.2** tier dungeon will be written **T8.1**
A real *T8.3** tier dungeon will be written **T8.2**

However, a T8 flat dungeon is correctly written T8 👍

_Refer to the exibit :_

![image](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/37340968/516edb51-d458-4391-b32f-ecfd445099ae)

**Comment by Faeeth** [comment]
I fixed it by changing the function **_SetLevelString_** in [src/StatisticsAnalysisTool/Dungeon/DungeonNotificationFragment.cs](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/blob/main/src/StatisticsAnalysisTool/Dungeon/DungeonNotificationFragment.cs)

    private static string SetLevelString(int level)
    {
        var levelString = level switch
        {
            0 => "",
            1 => ".1", // old .0
            2 => ".2", // old .1
            3 => ".3", // old .2
            4 => ".4", // old .3
            _ => ".?"
        };

**Comment by Triky313** [comment]
I'll try to explain it once for understanding.

Maps that can be purchased can look like this:

- T4.0
- T4.1
- T4.2
- T4.3

and of course from T5 to T8
So there are 4 different enchantment levels for a map.
However, there is another dungeon Open World that cannot be opened as a map, so let's call it T4 without .0

With that we have 5 different dungeons related to enchantments.

The difference between T4 and T4.0 is as follows:

- T4 = Enemies are 0% stronger
- T4.0 = Enemies are 16% stronger
- T4.1 = Enemies are 36% stronger
- T4.2 = Enemies are 58% stronger
- T4.3 = Enemies are 84% stronger

![image](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/14247773/0dd6766f-a179-45bb-a083-1edb337f9005)
![image](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/14247773/4c9eff50-4f4b-4567-8fb5-a7db0ea9d260)
![image](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/14247773/100ec34c-1fbc-49ef-9ea7-e52183ef2c0b)
![image](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/14247773/0b2589d3-936f-44e0-9219-1e2da5ff18f0)
![image](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/14247773/ac36ac39-cc70-4b55-a6a5-934a2adb5c92)
Sure we can debate whether the choice of diamond icons is a good one, but at this point I didn't have a better idea.
By the way, the diamonds are supposed to represent the butterflies from the dungeon.

**Comment by Triky313** [comment]
It's not a bug, everything is correct.
