### ISSUE TITLE
Silver reset after map change

### ISSUE THREAD

**Issue by Smyez** [Triky313/AlbionOnline-StatisticsAnalysis#365]
hi every time i leave a map this counter reset any idea ? im on the last update
![problemes](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/141528999/70183efc-e08c-4634-8fe1-f52352c75efe)

**Comment by Triky313** [comment]
Please update your tool!
You have v5.18.2 and the newest is v6.2.0!
https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/releases/tag/v6.2.0

**Comment by Triky313** [comment]
Even if you write that you are on the last update, it looks different on the screenshot.
If you continue to have problems with v6.2.0, report back here.

**Comment by Smyez** [comment]
not my Screenshot sorry ^^ but same problem on 6.2

**Comment by Triky313** [comment]
Okay, i'll check this

**Comment by Triky313** [comment]
I am currently unable to reproduce this bug.
If possible, please check again exactly how this happens and describe it as precisely as possible.
