### ISSUE TITLE
 'Item Search Screen'  favourited/ticked item/s sometimes disappear 

### ISSUE THREAD

**Issue by Barrymore-Pool-Attendant** [Triky313/AlbionOnline-StatisticsAnalysis#367]
I have checked multiple items in the Item Search list, sometimes after close/reopen off the app, i have the full list saved, so when i check 'show favourites' they appear no problem. Yet on other occasions, i have loaded AO stats, same process yet nothing has been saved or appears checked as favourites. i have used save in settings, used back-up, also run the .bat file, i don't know if I'm deleting my Fav items.json this way, somehow? Thanks.

 - OS: Win 10
 - Tool Version [6.2.0.22631] 
 - NPcap Version [WinPcap_4_1_3]

Item list, working no probs, as shown, somehow i am doing something that deletes maybe the user data .json files? a!![image](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/105766575/9f1d424d-6e0c-4f38-be96-9f08cc37a3ce)

![image](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/105766575/7a5af6f2-14ae-40e4-908b-908aef8d2a56)

**Comment by Triky313** [comment]
Currently I can't see any problem or reproduce it.
If you continue to have problems here, please write down exactly when and how it happened and what you did about it.
