### ISSUE TITLE
Conqueror Points No responding

### ISSUE THREAD

**Issue by bigbossbe** [Triky313/AlbionOnline-StatisticsAnalysis#374]
**Describe the bug**
When the applicaion is running, monery, experience are ok to be recorded. but the Conqueror Points keep show 0 when I get the conqueror point in the black zoon.

**To Reproduce**

**Expected behavior**
the Conqueror Points should be increase.

**Screenshots**
[Image](https://pasteboard.co/YC6oSl2dg52z.png)

**Desktop (please complete the following information):**
 - OS: windows11
 - Tool Version v6.3.1.31192
 - NPcap Version 4.1.3

**Additional context**

**Comment by Triky313** [comment]
Please update the tool to the latest version (v6.3.3) and it should work.
Fixed here 246838a8a5df3fa04b65822ec8cda185d492363a
