### ISSUE TITLE
select albion online main game folder  

### ISSUE THREAD

**Issue by AHMEDQWERTYUI** [Triky313/AlbionOnline-StatisticsAnalysis#392]
The program asks to locate the main game. When I select it, it shows me (Please select a correct folder) in red.
Can someone contact me on Discord? My name is AHMEDQWERTYU

**Comment by Triky313** [comment]
You have to select the root folder, not the folder "game".
Go one folder back and select it!

**Comment by AHMEDQWERTYUI** [comment]
thx

**Comment by AHMEDQWERTYUI** [comment]
can Add refining profit calculator
