### ISSUE TITLE
HCE map and level

### ISSUE THREAD

**Issue by Me1onSeed** [Triky313/AlbionOnline-StatisticsAnalysis#394]
Is it possible to detect HCE map and its level in dungeon tracking?

**Comment by Triky313** [comment]
Currently I'm working on adding the Mists and Mist Dungeons, when I'm done with that I'll try to improve the HCE map tracking.

**Comment by Triky313** [comment]
Done in 2acc4fa1ec9da7041d17b086c82d18113bb23b6b
