### ISSUE TITLE
Docker Image for macOS/ Linux ?

### ISSUE THREAD

**Issue by LaionFromNight** [Triky313/AlbionOnline-StatisticsAnalysis#398]
I wonder if it is possible to run it in a docker container? 

It could help a lot of players with macOS / Linux.
Thanks in advance for answering

**Comment by Triky313** [comment]
You cannot run a WPF application in docker.
Here is a snippet of the Microsoft docs
> Docker is for server applications—Web sites, APIs, messaging solutions and other components that run in the background. You can’t run desktop apps in Docker because there’s no UI integration between the Docker platform and the Windows host. That rules out running Windows Forms or Windows Presentation Foundation (WPF) apps in containers (although you could use Docker to package and distribute those desktop apps), but Windows Communication Foundation (WCF), .NET console apps and all flavors of ASP.NET are great candidates.

The only good way is actually AvaloniaUI #96
