### ISSUE TITLE
Add RU Locale

### ISSUE THREAD

**Issue by nikes** [Triky313/AlbionOnline-StatisticsAnalysis#4]
Hi, i translate program to ru locale.
Change .txt to .xml
[ru-RU.txt](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/files/5084117/ru-RU.txt)

**Comment by Triky313** [comment]
Update in https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/releases/tag/2.1.1
