### ISSUE TITLE
App does not open anymore, previously working.

### ISSUE THREAD

**Issue by Barrymore-Pool-Attendant** [Triky313/AlbionOnline-StatisticsAnalysis#404]
**Describe the bug**
I double click the .exe after freshly downloading and unzipping, it thinks for a brief moment, then nothing, it won't open it seems.. However I've never had a problem like this up until now, I've used the app for over 4 months, unsure if I had the latest update working tho. Okay, hope you can help with this thanks in advance.
 
**To Reproduce**
1.Double click the .exe
2.Nothing

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro Version: 22H2 Build: 19045.3324
 - Tool Version 6.3.4.0
 - NPcap Version (WinPcap) 5.1.76.719

**Additional context**
This is the freshly unzipped folder I created, I double click the .exe and it wont respond, however it did create a log folder with a .txt file i screen shot in the second pic.
![unzipped](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/105766575/41d52281-f523-4ed2-83e9-40f43a7278c3)
log details:
![unha](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/105766575/3aaadc35-e30d-4b22-bf17-17406e6f2596)

*Edit* Not sure if this information is relevant or not.
Source
Statistics Analysis Tool
Summary
Stopped working
Date
‎31/‎08/‎2023 11:02
Status
Report sent
Description
Faulting Application Path:	C:\ ALBION NEW TOOLS\StatisticsAnalysis-AlbionOnline-v6.3.4-x64\StatisticsAnalysisTool.exe

Problem signature
Problem Event Name:	APPCRASH
Application Name:	StatisticsAnalysisTool.exe
Application Version:	6.3.4.0
Application Timestamp:	6492041a
Fault Module Name:	KERNELBASE.dll
Fault Module Version:	10.0.19041.3324
Fault Module Timestamp:	6967c799
Exception Code:	e0434352
Exception Offset:	000000000002cf19
OS Version:	10.0.19045.2.0.0.256.48
Locale ID:	2057
Additional Information 1:	00c3
Additional Information 2:	00c31b3a8bdc043497ce4fb9a1c58281
Additional Information 3:	e52a
Additional Information 4:	e52a8e3e3530b1f8066cc4271d6f58f3

Extra information about the problem
Bucket ID:	3755f9fef35684a84ace33bc73e9e93f (1931538174680099135)

**Comment by Triky313** [comment]
hmm OnUnheandeldException without information.
You need to install also .net 7 https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-7.0.9-windows-x64-installer

In addition, reinstall NPcap ncoh once again, this can occasionally lead to problems.
