### ISSUE TITLE
Get the names and IDs of the players in the pack.

### ISSUE THREAD

**Issue by 3adrotPlay** [Triky313/AlbionOnline-StatisticsAnalysis#422]
In the "Party Builder" tab, I want to get all the names and ids of the players in the pack with one click.
Can this be done?
![изображение_2023-09-19_195850144](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/113040106/74b3d450-8f42-40a5-b735-a4b7ce0d7570)

**Comment by Triky313** [comment]
Pack? You mean Party right?

**Comment by 3adrotPlay** [comment]
you have already answered my question. I forgot to delete this post here.
https://media.discordapp.net/attachments/1147569007801684018/1153911862279290981/Screenshot_20230920_073150_Discord.jpg
