### ISSUE TITLE
Loot logger tab does not show or read the logs

### ISSUE THREAD

**Issue by Lightcram** [Triky313/AlbionOnline-StatisticsAnalysis#453]
**Describe the bug**
My logging tab registers the loot logs and can be exported to excel but the tool itself does not read and show the logs.

**To Reproduce**
1. Go to the tool
2. Click on logging

**Expected behavior**
Should be able to read and display the loot logs information

**Screenshots**
See attached
![for statistics tool](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/138783134/a1aa2ac0-d47b-4cf7-9099-a128a16955ba)

**Desktop (please complete the following information):**
 - OS:Win 10
 - Tool Version 7.0.2.19511
 - NPcap Version [e.g. 1.73]

**Comment by Triky313** [comment]
Look in the filter, are they activated?

**Comment by Lightcram** [comment]
Let me try.

**Comment by Lightcram** [comment]
I now know that you need to click the boxes. Thank you!
