### ISSUE TITLE
Live language adjustment when changing a language

### ISSUE THREAD

**Issue by lx78WyY0J5** [Triky313/AlbionOnline-StatisticsAnalysis#455]
The language on the right panel (Categories), did not change to the selected language when pressed save, as seen on the screen following

![StatisticsAnalysisTool_apcDYKwStO](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/84735589/2ee9a49e-0a2d-4741-9113-5c9ebd81df4a)

Step to reproduce

Select language (in my case French)
restart application
Select another language (in my case English US)
Press save

Even if prompted to restart app, the whole app already changed it's langue on the fly
Except this part which remain on the previous lang

**Comment by Triky313** [comment]
Yes, this is not yet perfectly implemented. Optimally, every translation should change immediately, I still need to implement that.

**Comment by Triky313** [comment]
Added in https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/releases/tag/v7.6.0
