### ISSUE TITLE
 A small problem requires a smart solution (RU)

### ISSUE THREAD

**Issue by KodokuVoid** [Triky313/AlbionOnline-StatisticsAnalysis#458]
**Describe the bug**
RU
Запуская приложение от имени администратора, пишет что отслеживание не работает, а внизу приложения пишет обратное - Запустите приложение от имени администратора. 
Папку игры указывал -> SteamLibrary\steamapps\common\Albion Online
US
When I run the application as an administrator, it says that tracking does not work, but at the bottom of the application it says the opposite - Run the application as an administrator. 
The game folder was indicated -> SteamLibrary\steamapps\common\Albion Online
**Screenshots**
![image](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/148903327/9f8a3d11-d932-44da-8978-2ee39714f43d)

**Desktop:**
 - OS: Windows 10 pro
 - Tool Version 7.0.3.18676
 - NPcap Version 1.78

**Comment by KodokuVoid** [comment]
US
After the update application to _7.1.0.27964_ it says **"Tracking is partially active (Please change location!)"**, but after changing location nothing happened.

**Comment by Triky313** [comment]
We are currently working on a solution with and without NPCap so that it works for everyone and everyone can decide for themselves what wants to use.

**Comment by Triky313** [comment]
Fixed 720bf9c1409ae9c9bfaf3c5091865cefcb79815e
