### ISSUE TITLE
Provide tracking via NPCap in addition to sockets

### ISSUE THREAD

**Issue by Triky313** [Triky313/AlbionOnline-StatisticsAnalysis#463]
Filtering like in Wireshark (DisplayFilters) are needed, or similar, so that players can track with VPN.
https://wiki.wireshark.org/DisplayFilters

What in any case does not need to be implemented again is the automatic selection of the game server West or East. 
I would query this as currently always at the first start and otherwise leave it in the settings.

**Comment by Kukkimonsuta** [comment]
Npcap version doesn't require administrator privileges, but the app is currently requesting them unconditionally and I strongly believe it should be allowed to run the app without administrator privileges.

Proposed solution:
1) start the app without administrator by default
2) check settings which sniffing method is selected
3) if it's npcap => do nothing; if it's sockets => restart app as admin

This should be done very early in the lifecycle, so for user the experience should be basically the same as now where he gets asked whether to allow admin or not without seeing anything earlier.

Is that behavior ok with you?

**Comment by Triky313** [comment]
@Kukkimonsuta 
You're right, with NPCap we don't need admin mode, yet it's currently stored in the manifest. 

I have no solution to start the tool and then check and then start admin or without admin.

In principle, we should then just set NPCap mode to default and everything else must decide the user himself.

**Comment by Kukkimonsuta** [comment]
To restart the app as admin without forcing it in manifest wen can do
```
Process.Start(new ProcessStartInfo { FileName = Environment.ProcessPath!, UseShellExecute = true, Verb = "runas" });
Environment.Exit(0);
```
It's not the most elegant, but it works.

Though now thinking more about it and maybe for now let's just keep forced admin + default sockets and see if my npcap implementation actually gonna be stable and revisit later.
