### ISSUE TITLE
Not really a feature request, but a question

### ISSUE THREAD

**Issue by AaronHo-0716** [Triky313/AlbionOnline-StatisticsAnalysis#478]
I would like to know how does the dps meter work? Like how it registers the damage from different players or fame / silver drops from mobs etc. This is so that I can maybe create a working Linux version, thanks.

**Comment by Triky313** [comment]
Take a look at the **CombatController** class, where you can find all the important methods for the damage meter.
I'm also working on the AvaloniaUi version, which will run on Windows, Mac and Linux when it's finished.
