### ISSUE TITLE
Parallels on an M1

### ISSUE THREAD

**Issue by marcfielding1** [Triky313/AlbionOnline-StatisticsAnalysis#479]
Hey I'm aware you've answered questions about Mac M1's before, I understand the .NET framework on that arch won't work, but is it likely to work on Parallels? Didn't wanna fork out for it if it wasn't going to!

FYI loving the trade monitor, I have noticed it doesn't always update without restarting the application, i'll have a bit more of a fiddle with it and file a bug report for though.

**Comment by Triky313** [comment]
Hay,
I can't answer that like that. The M1 with ARM is still relatively new and I will have to check that.

As soon as the Avalonia UI #96 version is ready and the tool runs on Mac, Linux and Windows, I'll check the compatibility for ARM.
