### ISSUE TITLE
Fame counting

### ISSUE THREAD

**Issue by iamzidane** [Triky313/AlbionOnline-StatisticsAnalysis#48]
The fame counted is always more than the real fame I got in albion, as exemple if I get 40k fame per dungeon in the dungeon tracker it shows 120k

**Comment by Triky313** [comment]
Hay @iamzidane,
Do you have a picture of it?
Did you kill a player while in the dungeon?
Are Satchel and Premium active on your account?
Is it about the total value in a dungeon in the list or about the main tracker above?

**Comment by iamzidane** [comment]
> Hay @iamzidane,
> Do you have a picture of it?
> Did you kill a player while in the dungeon?
> Are Satchel and Premium active on your account?
> Is it about the total value in a dungeon in the list or about the main tracker above?

![Starting fame](https://user-images.githubusercontent.com/83343341/116453193-1baa6780-a84e-11eb-8839-bcf2ea3e4d45.png)
![ending fame](https://user-images.githubusercontent.com/83343341/116453225-2664fc80-a84e-11eb-8f08-8bbf70b5810b.png)
![tool fame](https://user-images.githubusercontent.com/83343341/116453261-2fee6480-a84e-11eb-8c28-8ce8e90ca61f.png)
As you can see in the pictures above, the fame I got is 64 878 but the tracker indicates that I got 144 850.
I didn't kill any players, I don't use a satchel and premium is active.

**Comment by Triky313** [comment]
Okay good.
Did you play alone or with someone in a group?

**Comment by iamzidane** [comment]
> Okay good.
> Did you play alone or with someone in a group?

I was alone.

**Comment by Triky313** [comment]
So, I've tested it.
I have come to the following conclusion.
The fame that can be seen in the profile is calculated without premium and satchel.

Here is an example:
![image](https://user-images.githubusercontent.com/14247773/117306768-44e77b00-ae80-11eb-9c71-ef5b7be5d54c.png)
152,910,752 was my fame.
After killing a mob, I had 152,911,009 fame.
The difference is: **257**

541 was my fame according to Tool.
541 (total) - 129 (premium) = 412
412 - 155 (Satchel) = **257 Fame**

I will add an info window where this is mentioned. #50

**Comment by iamzidane** [comment]
![duplicate](https://user-images.githubusercontent.com/83343341/117311258-92a9b680-ae73-11eb-886d-4f89d5a874b3.png)

Actually I found the reason the counted fame is incorrect, I killed 1 mob and checked the tool recorded 2 mobs instead of one.

**Comment by Triky313** [comment]
Okay, I haven't noticed the problem yet. I'm trying to recreate that.

**Comment by iamzidane** [comment]
![dup 4](https://user-images.githubusercontent.com/83343341/117314560-67749680-ae76-11eb-8c5f-e7f4cf66a154.png)

It happens frequently

**Comment by Triky313** [comment]
Are you alone
It doesn't happen to me.

I just can't tell yet why you have this.

**Comment by iamzidane** [comment]
> Are you alone
> Do you use VPN?
> It doesn't happen to me.
> 
> I just can't tell yet why you have this.

I'm alone and I don't use VPN.

**Comment by Triky313** [comment]
I'll try to find the bug as soon as the ticket has been processed here. #51

**Comment by meybj** [comment]
i have this problem too, no satchel no vpn no auto respect

**Comment by Triky313** [comment]
Problem has been solved after the adjustments from #53.
If there are any other abnormalities, it will be opened again.
