### ISSUE TITLE
Tracking is partially Active (Please Change Zone!) WEST SERVER

### ISSUE THREAD

**Issue by HookShotz** [Triky313/AlbionOnline-StatisticsAnalysis#480]
The tool seems to not be working after I had reset it 3 times for a FF DPS meter I was doing as it just gave me the "Tracking is partially Active". I did look around the other forums for it, but I did not actually find anyways to fix it.

__For reference I__
-Am running it on Admin
-Went in and out of multiple zones
-Restarted the tool
-Reset all my data from yesterday and today (I just got it yesterday)
-Restarted my computer

But nothing had seemed to actually fix it.

**Desktop (please complete the following information):**
 - OS: Windows
 - Tool Version 7.2.0.0
 - NPcap Version 7.92

**Comment by Triky313** [comment]
Do you have VPN, if so switch it off.
Try NPCap mode instead of socket mode, you can change this in the settings.

But you have to install NPCap for this.
