### ISSUE TITLE
sorry what is that mean 

### ISSUE THREAD

**Issue by 6789-creator** [Triky313/AlbionOnline-StatisticsAnalysis#481]
<img width="164" alt="螢幕擷取畫面 2024-01-12 210701" src="https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/142524474/b00f1a91-850d-4b18-be10-8bf8043c1f01">

**Comment by Triky313** [comment]
Start the tool as Administrator in Windows. Make right click on the .exe file and start as admonistrator.
