### ISSUE TITLE
No prices for items

### ISSUE THREAD

**Issue by yoyoda2048** [Triky313/AlbionOnline-StatisticsAnalysis#482]
Hi
For a few days now, in the item search tab, I no longer see prices when I open the list for an item. This is one of the functions I use the most.
![Capture d'écran 2024-01-28 173731](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/120314258/92564da4-6c92-4a72-a60c-d831aa3731b6)

Everything else seems to be OK.

Same thing happens on my wife's computer
Tool version 7.2.1.24029
Packet provider ; socket
Windows 11

Regards

**Comment by Barrymore-Pool-Attendant** [comment]
Same issue, thanks in advance

**Comment by Triky313** [comment]
Unfortunately, SBI has encrypted some data so that many things no longer work.
I cannot say if or when this problem can be fixed

**Comment by yoyoda2048** [comment]
So sad but thanks for your reply and your work

**Comment by Triky313** [comment]
![image](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/14247773/41c08d67-3118-494b-acf5-89cb2bfa92fa)
Data should be displayed correctly again after the last update! https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/releases/tag/v7.3.3
