### ISSUE TITLE
Damage meter extension

### ISSUE THREAD

**Issue by Triky313** [Triky313/AlbionOnline-StatisticsAnalysis#49]
For the DPS meter, if possible, enable an option to create another tab for measurement from that time and posterior.

Like the DPS meter is working in a tab and then we can start another instance for dps meter for just a specific fight/boss or floor. In that way we could get results from all dungeon and for a specific floor, boss, or another occasion set by the player when pressed the "another instance like" button.

**Comment by zjy666-888** [comment]
rewer
