### ISSUE TITLE
Not really an "issue" but are we gonna get update for the EU server?

### ISSUE THREAD

**Issue by Sabayonte** [Triky313/AlbionOnline-StatisticsAnalysis#493]
Just like in the title :P

**Comment by Triky313** [comment]
As soon as there is Free2Play access, I can make an update.

**Comment by Sabayonte** [comment]
Awesome! Can't wait ❤

**Comment by Triky313** [comment]
https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/commit/48bce3f584c06162b04f639b0a554baf4aa76ea6
