### ISSUE TITLE
Dps Damage Meter not working

### ISSUE THREAD

**Issue by Fireshow666** [Triky313/AlbionOnline-StatisticsAnalysis#498]
**Describe the bug**
After recent ablion update, the damage meter no data

**To Reproduce**
the damage meter not woking 

**Screenshots**
![image](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/166284085/ac4aca63-b14d-4c48-a22f-e46b17226f0e)

all other functions are wokring expcet the damage meter, no record

**Desktop (please complete the following information):**
 - OS: WIN10
 - Tool Version V7.2V3.14962
![image](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/166284085/3feab360-4692-4e99-9b05-1ac952a31186)

**Comment by Triky313** [comment]
You have to activate the damage meter here 
![image](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/14247773/71b2d5ef-bf19-4585-b6cc-5279b8064921)

**Comment by Fireshow666** [comment]
oh my god. thank you so much.
