### ISSUE TITLE
[Question]How to display the best price on the starter list?

### ISSUE THREAD

**Issue by STILLCR4CK** [Triky313/AlbionOnline-StatisticsAnalysis#5]
Hi devs! 
I want to improve the program for myself. But I can't figure out how to call the variable with the best price from the ItemWindowViewModel.cs file.
Please tell me how i can do this

**Comment by Triky313** [comment]
In the file ItemControler.cs is a method named PriceStyle(bool bestSellMinPrice).

This method sets the style of the price, depending on whether the price is better or not.

`public Style SellPriceMinStyle => ItemController.PriceStyle(BestSellMinPrice);`
is used for example in "MarketCurrentPricesItem" and SellPriceMinStyle can be found in ItemWindow.xaml.

The Styles are in App.xaml.
