### ISSUE TITLE
[BUG] Dungeons Logger - Dungeon tier and enchantment

### ISSUE THREAD

**Issue by Kwelpinator** [Triky313/AlbionOnline-StatisticsAnalysis#502]
**Describe the bug**
Dungeon tier and enchantment aren't getting logged properly on dungeon scrolls.

**To Reproduce**
1. Use a dungeon scrolls on Albion Online
2. Enter your dungeon
3. Open the `Dungeons` tab on the Statistic Analysis Tool
4. Scroll to dungeon logger.
5. See error.

**Expected behavior**
It detected the dungeon tier and it's enchantment that I enter, even from a T7 zone, it could detect that I enter a T8 solo dungeon when using a scroll.

**Screenshots**
[Screenshot](https://cdn.discordapp.com/attachments/1210364164036501594/1233005150742777997/image.png?ex=662b8508&is=662a3388&hm=4eee6aa64e30f091c4bd153ba0c8af6d510c204384689a622c8b8dba6c941a3e&)

**Desktop (please complete the following information):**
 - OS: Windows
 - Tool Version v7.3.1.23829
 - NPcap Version : 1.7.6 (Not sure if this is the right one, I just look it up on my PC.)

**Additional context**
-

**Comment by Triky313** [comment]
This feature can no longer be supported because SBI has encrypted or removed the information for it.
