### ISSUE TITLE
[Request] Detailed Dungeon Loot Logging

### ISSUE THREAD

**Issue by Kwelpinator** [Triky313/AlbionOnline-StatisticsAnalysis#503]
**Is your feature request related to a problem? Please describe.**
Dungeon logger only log the most expensive item you get but we're unable to see all the items that we got from the dungeon chest.

**Describe the solution you'd like**
- Make it possible that when you hover your cursor over [the chest](https://prnt.sc/dpUXtmw3q_Jm) icon that show the value of your dungeon it will show an overlay that shows what loots you have got. Apart from hovering, make it also possible for us to click on [the chest](https://prnt.sc/dpUXtmw3q_Jm) icon so it is possible for us to scroll down on the overlay when we've got too much loot in one dungeon.
![image](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/128455792/3ec64b54-6197-4917-a64c-df94153d2dd0)

**Describe alternatives you've considered**
A new tab on the `Dungeons` tab where it only shows loot for the dungeons.
![mu_dungeon logger](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/128455792/74a511e9-ed62-4229-9d60-3c9e6091e8d1)
Here is a mockup I made which still has so many thing to improve. 
- [This part's](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/128455792/6a1d09aa-f3d9-4c87-813d-69d02b05d571) background can be related according to the type of dungeon (Hidden Caverns, mines, Sanctum, Undead).
- Add silver on top of the total value of the dungeon since silver can also be considered as loot.
- Add dungeon id/number so we can compare dungeon overview with dungeon loot tab.
- "Total" tab on dungeon overview, which represent time range of the dungeon shown, can be replaced with sorting method which include :
    - `Sort by Total Value` (Amount of loots in total silver value)

    - `Sort by Total Loot` (Amount of different loot)
    eg. dg1 = {[1] = rune, [2] = soul, [3] = relic} > dg2 = {[1] rune, [2] = soul}
    dg1 have more loots in types (3 types) compared to dg2 (2 types)

    - `Sort by Loot Quantity` (Total amount of loot)
    example
```lua
dg2 = {[1] = {["name"] = "rune", ["amount"] = 99},
       [2] = {["name"] = "soul". ["amount" = 99}}

       > --dg 2 have higher quantity of loot

dg1 = {[1] = {["name"] = "rune", ["amount"] = 1},
       [2] = {["name"] = "soul". ["amount"] = 1},
       [3] = {["name"] = "relic". ["amount"] = 1}}
```
dg2 have more loots in quantity (198 items) compared to dg1 (3 items)

**Additional context**
While editing the asset for the mockup, I realize this... 
![image](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/128455792/ce2e77ce-83ad-4b1a-bff0-90f96537dcc4)
PLEASE FIX THIS

**Comment by Triky313** [comment]
These are very good feature ideas. I'll take a closer look as soon as I have a new way of recognizing the enchantment levels of the dungeons.

**Comment by Triky313** [comment]
A list of items with a click on the chest has been added

To the point: `add silver to the total value of the dungeon, as silver can also be considered loot.`
This is already the case.

The green diamond is no longer used in the dungeon list, only in the settings as far as I can see. I don't see where to fix this.

For all other features please open a new issue.
