### ISSUE TITLE
Trade monitoring lose data

### ISSUE THREAD

**Issue by Nulllink** [Triky313/AlbionOnline-StatisticsAnalysis#507]
**Describe the bug**
Time to time with opening application trade monitoring tab doesn't show any previous data.

**To Reproduce**
1. Close application
2. Open without administrator
3. Close application
4. Open with administrator
5. Go to trade monitoring and it will be empty

**Expected behavior**
Data in trade monitoring doesn't delete if i open it without administrator.

**Screenshots**
I use app for a week almost, but have trades only from today.
![image](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/47364651/2b208871-7a7f-4d95-b27a-c040b59dc862)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Tool Version 7.3.2

**Comment by Triky313** [comment]
I cannot reproduce this case.
There was a case where data was deleted after an update, but this should no longer happen.

However, if I open the tool without administrator and then with , my data remains available, which does not change anything for me.

If you continue to have problems, save your data from the UserData folder and download the tool clean again.
