### ISSUE TITLE
Per hour calculations on dashboard are wildly inaccurate when runtime is over 1 hour

### ISSUE THREAD

**Issue by NathenSample** [Triky313/AlbionOnline-StatisticsAnalysis#510]
**Describe the bug**
As per title, once runtime is over an hour the per hour calculations become hugely inaccurate.
Machine is in the engb locale.

**To Reproduce**
1. Trip duration of over an hour, dashboard tab/any tabs displaying per hour metrics
2. Look at per hour values reported

**Expected behavior**
Correctly calculated per hour values

**Screenshots**
![ShareX_7ZITRuqNVc](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/9803552/bfc911c7-765b-49b5-a806-61ebb5fe83c6)

**Desktop (please complete the following information):**
 - OS: Windows
 - Tool Version: 7.3.3.7144
 - NPcap Version: 1.7.2

**Comment by Triky313** [comment]
Fixed in a4172564a09d93a771964d4496beccb8480ad0ae
