### ISSUE TITLE
double(or even 4 times) spending when buying goods

### ISSUE THREAD

**Issue by pzy2000** [Triky313/AlbionOnline-StatisticsAnalysis#512]
**Describe the bug**
![image](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/77827720/6f567dc2-35fa-4108-b0b0-348ffd636086)
When buying goods at the market, the logger logs it twice or even four times.

**To Reproduce**
1. Go to 'market'
2. Find something cheap
3. buy it

**Expected behavior**
normal

**Screenshots**
![image](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/77827720/cc3b0629-764c-4bd9-a8bc-a1044ffdb1ed)

**Desktop (please complete the following information):**
 - OS: Win11
 - Tool Version [v7.4.0](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/tree/v7.4.0)
 - NPcap Version 1.78

**Comment by pzy2000** [comment]
when selling goods, it is the same issue:)
![image](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/77827720/0c9979a7-86bc-44f0-806a-8dbb0d7970d7)

**Comment by pzy2000** [comment]
it is interesting that when I create a sell order, and check the mail when it is sold. It behaves normally.

**Comment by Triky313** [comment]
This is usually a problem with the network, something like VPN or similar.
But I'll see if I can avoid this in the tool.

**Comment by Triky313** [comment]
Fixed in 296cf4020bfe14347a2e68498c9a6aaa3a885012
