### ISSUE TITLE
I play from albion launcher and dont have folder ALBION ONLINE i only have game then Albion online data

### ISSUE THREAD

**Issue by Arhangelalx** [Triky313/AlbionOnline-StatisticsAnalysis#513]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Tool Version [e.g. 5.0.0]
 - NPcap Version [e.g. 1.6]

**Additional context**

**Comment by lucca257** [comment]
same problem: https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/issues/515

**Comment by Triky313** [comment]
I also play from the launcher.
I have no problem selecting the folder. It's the top folder itself, not inside the folder where game or battleeye is.

Of course, you may have renamed the folder during installation, in which case you would have to reinstall the game and name the folder exactly as it is actually called.

![image](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/14247773/1c27c867-aa63-47ab-ad36-671005ffd1f9)
