### ISSUE TITLE
Crash client

### ISSUE THREAD

**Issue by Ka4aH** [Triky313/AlbionOnline-StatisticsAnalysis#514]
**Describe the bug**
Client crashing when trying to open "Trade monitor" "Gathering" tab or any item in "Iteam Search" tab
 
**To Reproduce**
1. Go to 'Iteam Search'
2. Click on 'Any item'

**Expected behavior**
Expected to see opened tab

**Screenshots**
Video bottom below

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Tool Version v.7.4.0.26446
 - NPcap Version 1.79

**Additional context**
All at the video, problem started after one of the updates, can't remember which one, that been kinda long time ago
[Crash_client_record.zip](https://github.com/user-attachments/files/15752475/Crash_client_record.zip)

**Comment by Triky313** [comment]
Please download the tool again and only transfer your UserData from the old folder. If this continues to happen, your system may be experiencing problems.

I have more than 10000 entries in trades and no problems loading.

**Comment by Triky313** [comment]
It is possible that corrupt files were a problem here. Through further optimization and improvement I hope that this error will no longer occur in the future.
