### ISSUE TITLE
Can't install with Albion client only steam

### ISSUE THREAD

**Issue by lucca257** [Triky313/AlbionOnline-StatisticsAnalysis#515]
**Describe the bug**
On request to select the folder, it doesn't work. Only works on steam, my installation is from Albion client, not from steam.

**To Reproduce**
- on install, I can't select the launcher folder used by Albion client, only works with steam folder.

**Expected behavior**
Install the tool without steam

**Screenshots**
<img width="411" alt="image" src="https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/31326015/1ebbb13d-529a-4ed6-b516-f3a01b0e610c">
<img width="638" alt="image" src="https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/31326015/c13d7a07-bea0-4a29-8439-783a44b9b09e">

**Desktop (please complete the following information):**
 - OS: [windows 11]
 - Tool Version [-v5.11.0-x64]
 - NPcap Version [latest]

**Additional context**
None

**Comment by Triky313** [comment]
Answer here #513

The folder in your picture definitely has nothing to do with Albion Online, you are completely wrong.
