### ISSUE TITLE
Tracking doesn't work when using VPN - GearUP Booster

### ISSUE THREAD

**Issue by Hiksys** [Triky313/AlbionOnline-StatisticsAnalysis#517]
Good afternoon, tracking does not work when using VPN - GearUP Booster, even when using tracking via Npcap.
npcap version - 1.79
Runtime version - 8.0.0
StatisticsAnalysis version - 7.1.0

**Comment by Triky313** [comment]
This is because your VPN provider is probably changing the IPs to Albion. You have to find out what the IP to your Albion server is via VPN and then enter it in the filter!

**Comment by Hiksys** [comment]
thanks for the answer, now I need to understand how to find out the server
ip through my VPN)

вт, 11 июн. 2024 г., 14:31 Aaron Schultz ***@***.***>:

**Comment by Hiksys** [comment]
To be honest, I have no idea how to do this, for example, I am currently connected to the node via VPN - Moscow, RU > Frankfurt, DE 05. I don’t understand how to determine the ip

**Comment by Triky313** [comment]
Unfortunately, I can't tell you exactly. Every VPN is different.
Some players have found this out using Wireshark. Maybe you can try it with that.
