### ISSUE TITLE
Doesn't or fully show the party you are in unless you are the last one to join

### ISSUE THREAD

**Issue by gimbolark** [Triky313/AlbionOnline-StatisticsAnalysis#521]
**Describe the bug**
Doesn't or fully show the party you are in unless you are the last one to join or if you joined the party before you opened the application

**To Reproduce**
1. Join a party
2. Open the application
3. Change zones to make tracking active

**Expected behavior**
Should show the whole party

**Screenshots**
![image](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/40950342/3fba3528-b9fe-40c1-9112-bb8b1208ed8f)

**Desktop:**
 - OS: Win 10 - 22H2 - 19045.4529
 - Tool Version v7.5.4.20700
 - NPcap Version 1.79

**Additional context**
Changing packet provider to NPcap doesn't change anything

**Comment by Triky313** [comment]
First you have to open the tool, then you have to change the map and then join the party!
The green text must be at the top of the tool, otherwise the tool is not completely active!
