### ISSUE TITLE
hallo，Triky313，Can you add European Servers in AlbionOnline-StatisticsAnalysis？

### ISSUE THREAD

**Issue by thebiggestmagichands** [Triky313/AlbionOnline-StatisticsAnalysis#522]
hallo，Triky313，thank you for readed this matters. Can you add European Servers in AlbionOnline-StatisticsAnalysis？I know it may be worry for you， if it ture i am so sorry. 
Andthen，Can I get a handbook for add European Servers --Function --in  AlbionOnline-StatisticsAnalysis？
best regard

**Comment by Triky313** [comment]
Hello,
download the latest version of the tool, as the Europa server has been supported for some time.
