### ISSUE TITLE
Incorrect dungeon enchantment displayed

### ISSUE THREAD

**Issue by Marvun** [Triky313/AlbionOnline-StatisticsAnalysis#523]
**Describe the bug**
The tier/enchantment of the dungeon is visible, but it isn't quite correct. The butterflies are correct and match what the enchantment of the dungeon is, but the number/color of the number does not. Green should be.1, blue .2, pink .3 and gold .4 no?

**To Reproduce**
1. Go to the dungeons tab.
2. Enter an enchanted dungeon.
3. You can see that the color of the butterflies is correct but the number in the tier is not.

**Expected behavior**
The number and its color should match the correct enchantment level.

**Screenshots**
![image](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/56234595/a3cba42f-31fa-48cc-a88f-c6c1c0528e0c)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Tool Version 7.5.5
 - NPcap Version -----

**Comment by Triky313** [comment]
The reason why this is the case is explained here. #350
