### ISSUE TITLE
Storage history

### ISSUE THREAD

**Issue by Nox188** [Triky313/AlbionOnline-StatisticsAnalysis#528]
**Describe the bug**
During entering the bank history for all bookmarks in the storage history related to this bacnk are cleared and the main bookmark is only updated.

**Expected behavior**
Only the bookmark which was viewed should be updated, the rest shoud be unchanged.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Tool Version 7.6.0.34379

**Comment by Triky313** [comment]
Done 7f4bbe50f89c03aef569b963f8fc544b7cb33f5c
