### ISSUE TITLE
Wrong item display

### ISSUE THREAD

**Issue by weteranxd** [Triky313/AlbionOnline-StatisticsAnalysis#529]
**Describe the bug**
Wrong item display for example when i gather 3.0 skin it shows i gathered 7.2 sunflax
**Screenshots**
![image](https://github.com/user-attachments/assets/fa425e67-1daf-4628-8a52-5e062f7c200c)

**Desktop:**
 - OS: [e.g. Windows 11]
 - Tool Version [e.g. 7.7.0.21563]
 - NPcap Version [e.g. 1.6]

**Comment by Triky313** [comment]
You must have installed Albion Online twice and not updated one of the two games. 
Then, if you assign this game to the tool, the wrong files will be displayed.

**Comment by weteranxd** [comment]
thx i will delete all albions and install again
