### ISSUE TITLE
StatisticsAnalysisTool dont opening

### ISSUE THREAD

**Issue by HatsuneM1ka** [Triky313/AlbionOnline-StatisticsAnalysis#532]
**Describe the bug**
StatisticsAnalysisTool dont work

**Expected behavior**
Open the StatisticsAnalysisTool

**Screenshots**
Its video https://youtu.be/oy-dmj0tSh0
**Desktop (please complete the following information):**
 - OS: [win10]
 - Tool Version [7.7.3]
 - NPcap Version [1.79]

**Additional context**
i open the StatisticsAnalysisTool.exe and nothing opening

**Comment by HatsuneM1ka** [comment]
yes it also installed i use StatisticsAnalysisTool on long time and today on morning its dont opened

**Comment by 613my** [comment]
I also encountered the same problem. After clicking, it can't be opened. Is there a new solution now?

**Comment by HatsuneM1ka** [comment]
reinstall windows now it work

**Comment by 4ung** [comment]
I am Having the Same Problem in My Win 11 PC.
Its Work Perfectly in Win10.
What should i do ?

**Comment by Triky313** [comment]
It looks more like an anti-virus tool or something similar is blocking the tool.
It may also help to completely re-download the tool and update it to the latest version!

I have tested it myself on Windows 11 and it runs without any problems.

**Comment by Triky313** [comment]
Sounds like an anti-virus problem.
Switch it off to test it.
If it then runs, you need to whitelist the tool in AntiVirus.
