### ISSUE TITLE
Not finding HQ bank tabs in storage history

### ISSUE THREAD

**Issue by Gerow693** [Triky313/AlbionOnline-StatisticsAnalysis#534]
Hello, first of all, love your project very useful, great work.

**Is your feature request related to a problem? Please describe.**
In storage history I am not finding chests from Headquarters
I am not sure if it is a bug or just technical constraint, so i'm posting it as feature request.

**Describe the solution you'd like**
In the current storage history tab, have Headquarters / Hideout map (my specific use case is headquarters)

**Describe alternatives you've considered**
Checked my whole chests tab and didn't find my HQ chest.

**Additional context**
HQ map is everwinter plain, not found in the list

![image](https://github.com/user-attachments/assets/334a914e-0042-49cf-ac09-3823deb86059)

Have a good day :)

**Comment by Gerow693** [comment]
Noticed today, it is fixed !

**Comment by Triky313** [comment]
Fixed in 9c3ba96cd9dc27f5cb7a8cde442eb31dec41a480
