### ISSUE TITLE
BSOD Crash

### ISSUE THREAD

**Issue by DaniSheng** [Triky313/AlbionOnline-StatisticsAnalysis#535]
**Describe the bug**

**To Reproduce**
1. Changing between  browser's window and tool's window
2. Crash and BSOD and restarting the system, in random time
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 updated
 - Tool Version Latest version

**Additional context**

**Comment by Triky313** [comment]
I can neither reproduce this problem nor has it ever occurred with a player.
I strongly suspect that you have a problem with your system.

Also, more information is needed for the next time. The fact that you used the latest version of the tool is good, but it doesn't tell me which version it was.
Please provide more information about the incident in the future and upload logs if necessary.
