### ISSUE TITLE
Application stopped working

### ISSUE THREAD

**Issue by AntyZhyk** [Triky313/AlbionOnline-StatisticsAnalysis#539]
Source
Statistics Analysis Tool

Summary
Application stopped working

Date
10/29/2024 0:00

Status
Report sent

Description
The application periodically closes on its own. In the Event Log, I see the following error. I have tried the following troubleshooting methods:

1. Windows Update and Driver Check: Ensuring your OS and drivers are fully updated to fix any incompatibility with KERNELBASE.dll.
2. Reinstalling the Program: Uninstalling and reinstalling StatisticsAnalysisTool to fix any potential issues with application components.
3. Running as Administrator: Running the program with elevated privileges to prevent access issues.
4. Compatibility Mode: Enabling compatibility mode for the application.
5.System File Checker (SFC): Running sfc /scannow in Command Prompt to repair missing or corrupted system files.

Invalid application path: E:\Downloads\StatisticsAnalysis-AlbionOnline-v7.1.0-x64\StatisticsAnalysisTool.exe

Problem Signature

Event Name: APPCRASH
Application Name: StatisticsAnalysisTool.exe
Application Version: 7.7.4.0
Application Timestamp: 66960000
Faulting Module Name: KERNELBASE.dll
Faulting Module Version: 10.0.19041.4957
Faulting Module Timestamp: c5225d0f
Exception Code: e0434352
Exception Offset: 000000000003b699
OS Version: 10.0.19045.2.0.0.256.48
Locale ID: 3072
Additional Information

Additional Information 1: 57c1
Additional Information 2: 57c1dc6bc95b1f75381bc6f146fafddf
Additional Information 3: a149
Additional Information 4: a149d2e35a3e2acd0a6370b56ee599f3
Problem Details

Container ID: 40e3e41c819c3a9c53f329e629489ce2 (1437538774573161698)

**Comment by Triky313** [comment]
It is often antivirus programs that prevent the app from starting. Please check whether this could be the cause.
