### ISSUE TITLE
Keep your dependencies up to date for free, yours faithfully, a fellow dev!

### ISSUE THREAD

**Issue by PhilipAbed** [Triky313/AlbionOnline-StatisticsAnalysis#541]
Hi, i'm a fellow developer and albion player as well, hit me up ingame as well. ( ign: StinkyLord ), i love what you do here, keep up the good work!

I work in cyber security, and to keep you safe you should use this free tool:
https://github.com/renovatebot/renovate

You should install it, it has automatic dependency updates for any project, i can be your contributor to help keep this program non-vulnerable, for any questions or help let me know.
It's free 100% i contribute to open source projects like this

to install:
https://github.com/apps/renovate

for full docs [docs.renovatebot.com](https://docs.renovatebot.com/)

It will open a PR automatically explaining what it does.
furthermore. it has a nice UI that i work on, current link is: https://developer.mend.io/
 
If you want i can help set it up if something is missing. let me know! glad to help!

i tried to fork it and look at this for reference:
https://github.com/PhilipAbed/AlbionOnline-StatisticsAnalysis/pull/1

**Comment by Triky313** [comment]
Hi,
thanks for the tip, but I think I can manage without it for now.
The tool is not big enough and not developed by many people to make it worthwhile at the moment.
