### ISSUE TITLE
Russian symbols don't work

### ISSUE THREAD

**Issue by Valkalas** [Triky313/AlbionOnline-StatisticsAnalysis#6]
Windows 10
After last update doesn't work russian translation
Wrong encoding for windows?

![16-09-2020_14-26-24_gixlt](https://user-images.githubusercontent.com/1575688/93331684-587a9e80-f829-11ea-9741-a004bc97c5e2.png)

**Comment by Triky313** [comment]
Hay,
please test the latest version and say me if the problem is gone.
https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/releases/tag/2.2.2

**Comment by Triky313** [comment]
After you have the new version, you have to delete the "ItemList.json" file from the folder. Then restart the tool.

https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/releases/tag/2.2.2

Then all languages should be displayed correctly again.

**Comment by Valkalas** [comment]
Yes, it's work. Thank you!

**Comment by Valkalas** [comment]
Hm.. After closing program, in next run, error repeat :(
If before run deleted "ItemList.json" then all okay, but every time delete this file before run program... If possible - fix it please :)

![18-09-2020_11-54-48_u8rgg](https://user-images.githubusercontent.com/1575688/93578307-d5cb1e00-f9a5-11ea-998c-7697696d5168.png)

**Comment by Triky313** [comment]
Fix in https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/releases/tag/2.2.3

**Comment by Valkalas** [comment]
Now it's worked) Thank you so much!
