### ISSUE TITLE
The Chests Totals on the Dungeon Tracking page doesn't seem to update on its own

### ISSUE THREAD

**Issue by ChakraaArcana** [Triky313/AlbionOnline-StatisticsAnalysis#64]
**Describe the bug**
The Totals on the Dungeon Tracking page doesn't seem to update on its own.
The Number of dungeons ran will updateon its own, but none of the chests totals.
Relaunching the app will update it.

**To Reproduce**
1. Open the App
2. Start the Tracking
3. Clear a dungeon

**Expected behavior**
The looted chests totals should be updating as we go.

**Screenshots**
![image](https://user-images.githubusercontent.com/10036932/122024671-a57aa980-cd96-11eb-921e-b36d8f40b294.png)
![image](https://user-images.githubusercontent.com/10036932/122025970-d14a5f00-cd97-11eb-91d0-3ccf8008226c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: v3.7.1.15575

**Comment by Triky313** [comment]
@ChakraaArcana 
I have now implemented the UpdateUI method in other places in order to get an update for the UI more frequently.
Basically, an update should always happen when changing maps or discovering a chest / shrine.
