### ISSUE TITLE
corrupted dungeon, Timer stop after first floor

### ISSUE THREAD

**Issue by Wildgear** [Triky313/AlbionOnline-StatisticsAnalysis#66]
I poped my food once inside of both runs. and after going to the next floor in the corrupted dungeon.  the Dungeon timer stops that chest tracker, fame, and silver tracker are all still working.

on a side note after you see more than one type of chest it would be nice to have a counter for each found. I have pushed the Dungeon time before all the way off

![Capture](https://user-images.githubusercontent.com/19192397/123741562-c2af7d80-d856-11eb-83c8-98fec2539377.PNG)

**Comment by Triky313** [comment]
Hay @Wildgear 
I don't think I fully understand the problem yet. Can you explain it in a little more detail?

Normally, each level in a currupted dungeon should create a new dungeon tracker row.
I can't keep Corrupted on one line at the moment, otherwise we'll have 50 chests in a row at some point.

**Comment by Triky313** [comment]
Okay, now understand the problem.
I will take care of it as soon as possible.
