### ISSUE TITLE
Allow tracking to reset party member list

### ISSUE THREAD

**Issue by FlyingJetski** [Triky313/AlbionOnline-StatisticsAnalysis#68]
Currently when I'm tracking the game for DPS meter, it's difficult to include all party members (I'm doing ava and the party list only has 3 people even though we have 20).

So a feature that would be nice is to have a button that allows us to reset  or refresh the party member list. If it is something that cannot be done from the information available from the game, can you at least put up an info guide on how the party member list works so we can try to follow the proper procedures to include everyone in the party (e.g. Be the first in the party, turn on the tracker, and invite people)

**Comment by Triky313** [comment]
Unfortunately, this is not that easy to implement.
There is an info button on the right. If this information is not enough, I can gladly expand it again.

![image](https://user-images.githubusercontent.com/14247773/125277440-b543ca00-e311-11eb-925e-6c1c46cc38b9.png)
