### ISSUE TITLE
Actual log from the loot logger

### ISSUE THREAD

**Issue by sh1ny** [Triky313/AlbionOnline-StatisticsAnalysis#69]
**Is your feature request related to a problem? Please describe.**
The loot logger is primarily useful during activities like:

1. ZvZ
2. Ava dungeons

To make use of the log, people use sites like aolootlog.com or https://matheus.sampaio.us/ao-loot-logger-viewer/

to upload and save the data.

**Describe the solution you'd like**
Make all the loot get logged into a csv file, with the same format that the above sites expect and read.
Make it so you can press a shortcut ( or a button on the app ) and start/write a new log file.

**Describe alternatives you've considered**
Look through the lootlog in the app window and despair that you can't compare it with your guild chests' log.

**Additional context**
Nothing more to add :P

**Comment by Triky313** [comment]
I tried the page https://matheus.sampaio.us/ao-loot-logger-viewer/ and unfortunately got no results. I can't say exactly which format is needed there.

There are definitely plans to add more features to the lootlogger. Of course I can export a file, that's no problem. I just couldn't find exactly what format you need there. Except for the format from the game itself.

As additional information: I can see collected loot from players and mobs. Loot from chests is a different matter, it's not that easy to do.

Can you send me a file that works?
I would like to see that.

**Comment by sh1ny** [comment]
About the chest and other logs, this should help:

https://github.com/albion-packet-hooking/AlbionPacketHandler

**Comment by Triky313** [comment]
Thank you, that looks interesting. I'll take a look at this.

**Comment by Triky313** [comment]
Implement together with the #41

**Comment by Triky313** [comment]
First precautions have been taken to be able to track local player loot.
