### ISSUE TITLE
Excuse me, can you help me solve this problem

### ISSUE THREAD

**Issue by hnzero001** [Triky313/AlbionOnline-StatisticsAnalysis#7]
Hello

 
![5](https://user-images.githubusercontent.com/21352901/97673248-69742c00-1ac6-11eb-89be-7400d95b8f71.png)
Is there a proper way to display my search results in Zh CN,

The current interface is already in CN language. There is something wrong with the category name displayed.

                                                                                                                                            Thanks

**Comment by Triky313** [comment]
Hi @hnzero001 ,
can you send me your translation file? Then I can test it. :)

**Comment by hnzero001** [comment]
I use version 2.2.3. I can't run the 2.3 program on my computer. I can't set the language. The program crashes. I wonder if this is the cause.

**Comment by Triky313** [comment]
I understand the problem.
But once I need the language file .txt from your folder with your language. I don't have this.

I'm also looking at the problem with the crash.

**Comment by Triky313** [comment]
Hi @hnzero001,
i have a new version that hopefully won't crash anymore.
https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/releases/tag/2.3.1

The item names should now also be displayed in zh-CN.

When you add a new language file, the language code must be just right and exist. Your file must be called "zh-CN.xml".

If you have any further problems, please open a new ticket.

**Comment by asdf0475** [comment]
Hello
This issue also occurs in Korean settings.
How can I fix it? (using V5.0.0.33154)
And I looked at en-US.xml and modified it myself to create ko-KR.xml.

[https://raw.githubusercontent.com/broderickhyman/ao-bin-dumps/master/formatted/items.json] There is KO-KR among the LocalizedNames fields in the content, and the 2Byte language system is used just like Chinese.
That's why I think it's possible, but it's not.

**Comment by Triky313** [comment]
Please note that the text in the tool has nothing to do with the item names. Item names are taken directly from the game files. 

"LocalizedNames": {
    "EN-US": "Hideout Construction Kit",
    "DE-DE": "Unterschlupf-Baukasten",
    "FR-FR": "Kit de construction de repaire",
    "RU-RU": "Набор для постройки убежища",
    "PL-PL": "Zestaw do budowy Kryjówki",
    "ES-ES": "Kit de construcción de escondites",
    "PT-BR": "Kit de Construção de Esconderijo",
    "ZH-CN": "藏身地堡建筑工具包",
    "KO-KR": "은신처 건설키트"
  },

With the example file you can see which languages are supported, if your language is included but the item names are not displayed in the correct language, then I have to take a closer look.

ZH-CN should actually be displayed. The language file must then also be called that.
If necessary, I can add an option where the item names can be manually set to another language.

**Comment by asdf0475** [comment]
sorry, i don't understand.
I am Korean And use the "ko-KR" language.
Why can't I get the Korean item list from the item list json url?
Obviously the item list json has information about "ko-KR".
And the example code also has some information about "ko-KR".
But I can't get the Korean item list.
