### ISSUE TITLE
DPS meter cannot be streamed on Discord

### ISSUE THREAD

**Issue by FlyingJetski** [Triky313/AlbionOnline-StatisticsAnalysis#70]
When streaming the DPS meter on Discord, it shows only a black screen

![2021-07-22 15 49 09](https://user-images.githubusercontent.com/49599589/126612825-6ded7ee6-1c9f-4161-a213-68ad3b1cf7a0.png)

**Comment by FlyingJetski** [comment]
After tinkering with the project, the stream shows a black screen because of the AllowTransparency=True property in MainWindow.xaml.
This, however, causes the window to have a small white control bar remaining and allows the user to resize from the sides of the window
![image](https://user-images.githubusercontent.com/49599589/126626207-47222bf0-491e-42d3-bd4a-4c6e5f1c4732.png)

**Comment by Triky313** [comment]
I have now added an external window which can be opened in the DamageMeter area.
You should be able to stream the special window.
