### ISSUE TITLE
Healing meter is not accurate for certain situations

### ISSUE THREAD

**Issue by FlyingJetski** [Triky313/AlbionOnline-StatisticsAnalysis#71]
There are a couple of reasons why people want a DPS and healing meter. 
First is to measure their damage or healing amount since there are no training dummies or scarecrow targets to test on.
However, there are also people that use these meters to check whether or not the party members are doing their job. This is commonly found in HCE / Avalonian Raids.
Since the healing meter records ALL healing outputs, a Fallen Staff healer that uses their E on the party on full health will have a higher healing output compared to a Fallen Staff healer that uses their E only when the party is low.
It would be nice if there is an option that allows us to toggle the type of healing recorded (i.e. healing output vs healing done)

**Comment by Triky313** [comment]
To be honest, I haven't tested that yet.
I'll take a look at this.

**Comment by Triky313** [comment]
That was actually a bug. It should of course only be the case that the healing is scored if the affected player's lives are not full.
