### ISSUE TITLE
GNU/Linux binary, build instructions?

### ISSUE THREAD

**Issue by mashu** [Triky313/AlbionOnline-StatisticsAnalysis#75]
Hi,

AlbionOnline is also a game that runs natively on GNU/Linux.
Would you provide a static GNU/Linux binaries or build instructions?

**Comment by Triky313** [comment]
WPF cannot currently be used for Linux.
In addition, I would have to update the .net framework to at least 5.0.
Then there are countless references to other projects that are not yet running on Linux.

Maybe MAUI would soon be a solution, but I have to read it first.

It will probably not come to that in the foreseeable future. I will look for more good solutions, but the effort is just too big at the moment.

**Comment by Triky313** [comment]
I took a look and Avalonia would be one way of tackling the whole thing. It's definitely a big hassle, but I'll add that to my list.

**Comment by Tyrben** [comment]
I trigger on updating to .NET 5.0 for the same subject: being able to compile and use it on Linux (5% of the gamers).
This looks a better idea than rewriting for Mono.

**Comment by Triky313** [comment]
WPF cannot be started under Linux, we will probably not be able to avoid having to rewrite the tool.

**Comment by Triky313** [comment]
I will have to switch from WPF to Avalonia for this.
Unfortunately, the whole project is affected, so it's a huge task. I can't tell you when it's coming.
