### ISSUE TITLE
Could we get chat from guild channel chat?

### ISSUE THREAD

**Issue by huynpase** [Triky313/AlbionOnline-StatisticsAnalysis#76]
Hi Triky,

Thank for your hard work!
Could i ask i can get guild channel chat?

**Comment by Triky313** [comment]
Do you want to see the guild chat in the tool?

**Comment by huynpase** [comment]
Hi, no i'm not. I just want to get chat into my discord. But i try to add chatmessage event but it didn't work :D

**Comment by Triky313** [comment]
I guess I don't understand exactly what you mean. Can you explain again exactly what you would like to have?
