### ISSUE TITLE
HCE team mates evaluation

### ISSUE THREAD

**Issue by salucci** [Triky313/AlbionOnline-StatisticsAnalysis#77]
Currently to find members for an HCE team it is difficult to know if the DPS has good damage or if any member is a troll (no fee, A out after death etc)

it would be really cool if at the end of the map we could evaluate the performance of the team partners

currently we only have the option to search for the person's nick in HCE discords, blacklists etc, but we are never sure if it really is a bad player or if it was a false report. And after this (even if player is not troll) we dont have to know if player plays good at that role.

things to consider: 
Is it possible to identify by software that the map the person entered is an HCE?

Is it possible to identify by software the level of the map? 1-18

when registering on database the avaliaton columns that would have  ( uniqueID(int),  CharIdUser(int), CharIdTargetOfAvaliation(int), HCEtier (int - if avaiable), RolePerformance(int), Notes(varchar - nullable), isLeaver(bool), isFeeDodger(bool), isToxic(bool), dateTime(dateTime mm-dd-yyyy hh:mm:ss)

I have knowledge in C# and I'm avaiable to discuss and give ideas to this new feature
discord: Salucci#7021

**Comment by Triky313** [comment]
Hi,
Do I understand correctly that you want a system where you can see if the players in your group are good or bad for an HCE?
If so, the following should be clarified.

Where is the data written to? Only locally for the person using the tool as a help for future HCE's?
That would be at least the only thing I can think of, for everything else we would need an external database.
Or there is a way to add the database in the tool without me having to create one. So by URL.

I don't know if I can see what level the HCE has, I don't think so. I haven't found a good solution for Dungeon Tier's either, so we still have to look for a solution.

**Comment by salucci** [comment]
At first my idea is to record an external database (perhaps by a simple http post), so we can in the future view this data either in the tool (when the user enters the group) or through a website search for the character's nick

**Comment by salucci** [comment]
![albiontool1](https://user-images.githubusercontent.com/14095138/130512594-56306969-e7f3-49eb-8586-5f30db1371ae.png)

![albiontool2](https://user-images.githubusercontent.com/14095138/130512603-c988f56f-199c-4859-bed9-43cad7d5beeb.png)

**Comment by Triky313** [comment]
What bothers me a little is the external database. The more external connections there are, the more vulnerable the tool is.
Other options should be considered here.

The problem will be that many will try to manipulate the data. It will be an enormous effort to prevent this.

**Comment by salucci** [comment]
true, many people could fake post using others charID
