### ISSUE TITLE
Market tool interact with game

### ISSUE THREAD

**Issue by Blixtmen** [Triky313/AlbionOnline-StatisticsAnalysis#78]
Hello! Just wondering if the application has any interactions with the game client, if you are only using it to look at prices?
Without using any tracking/DPS meter etc. Just to be 100% safe =]

**Comment by Triky313** [comment]
If tracking is not used, there will be no interaction with the game.
The prices for items from the auction houses are from an external database of albion online data project.

Without a tracker, the tool is 100% save.

**Comment by Blixtmen** [comment]
Thanks!
