### ISSUE TITLE
History tab is broken

### ISSUE THREAD

**Issue by Blixtmen** [Triky313/AlbionOnline-StatisticsAnalysis#79]
This window seem to be broken on all items
![image](https://user-images.githubusercontent.com/20008760/130528846-0c51199e-3649-470d-936c-bc191e5aa695.png)

**Comment by Triky313** [comment]
Currently you have to deactivate and activate a quality checkbox when the history tab is open. Then the tool should show something.

The history tab will be removed in the next version. The framework behind it is out of date and I have to rebuild it.

I am working on it. #80
