### ISSUE TITLE
Dungeon's tracking after 4.0.0 update

### ISSUE THREAD

**Issue by MickaelOth** [Triky313/AlbionOnline-StatisticsAnalysis#81]
Hello,

I've made the 4.0.0 update some hours ago and found out a bug. It seems like Silvers, Silvers/h, Fame/h and ReSpec/h in dungeon's history are not well tracked (including those tracked before I've updated the tool).

![StatisticsAnalysisTool_2021-09-01_12-29-07](https://user-images.githubusercontent.com/30047420/131656188-f9d92fc6-e3b3-4e78-a960-7f71faed187c.png)

The last two has been tracked before the update (they've like 1 or more [fame/respec/silver]/h) , the others has been made after (0 [fame/respec/silver]/h).

Anyway, thank you for your awesome work, incredible tool ! 😀

**Comment by Triky313** [comment]
Fixed bug with version 4.0.1. :)
