### ISSUE TITLE
Link Download Win10 Crash

### ISSUE THREAD

**Issue by GiuseppeFantoni** [Triky313/AlbionOnline-StatisticsAnalysis#82]
Link Download Win10 Crash

**Comment by Triky313** [comment]
Can you explain your problem in more detail?  so unfortunately I can't help you!

**Comment by Itsadreamtocode** [comment]
If you go to the download links on this page, for 4.01 the links give 404 errors rather than downloading a .exe is I think what they are saying because that is what happens to me too

**Comment by Triky313** [comment]
Fixed it.
