### ISSUE TITLE
When this problem occurs, which configuration link should be updated? How to solve this problem?

### ISSUE THREAD

**Issue by hnzero001** [Triky313/AlbionOnline-StatisticsAnalysis#9]
![s1](https://user-images.githubusercontent.com/21352901/99147946-cb848200-26bf-11eb-9a37-81e99e4ae950.png)

**Comment by Triky313** [comment]
Hi,
First delete the "ItemList.json" file from your tool folder, if it is still there.

Next look in the settings for the setting "Item list source url" in the tool. Here is usually the default link which reads as follows: https://raw.githubusercontent.com/broderickhyman/ao-bin-dumps/master/formatted/items.json

If you have any further problems, please contact me again.
